# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainGui(object):
    def setupUi(self, MainGui):
        MainGui.setObjectName("MainGui")
        MainGui.resize(1623, 739)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainGui.sizePolicy().hasHeightForWidth())
        MainGui.setSizePolicy(sizePolicy)
        MainGui.setMinimumSize(QtCore.QSize(1623, 739))
        MainGui.setMaximumSize(QtCore.QSize(1623, 739))
        self.centralwidget = QtWidgets.QWidget(MainGui)
        self.centralwidget.setMaximumSize(QtCore.QSize(1623, 698))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.Main_Frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_Frame.sizePolicy().hasHeightForWidth())
        self.Main_Frame.setSizePolicy(sizePolicy)
        self.Main_Frame.setMaximumSize(QtCore.QSize(1623, 698))
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Frame.setObjectName("Main_Frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Main_Frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_volume = QtWidgets.QFrame(self.Main_Frame)
        self.frame_volume.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_volume.setMaximumSize(QtCore.QSize(307, 833))
        self.frame_volume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_volume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_volume.setObjectName("frame_volume")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_volume)
        self.verticalLayout.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_volume_title = QtWidgets.QLabel(self.frame_volume)
        self.label_volume_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volume_title.setObjectName("label_volume_title")
        self.verticalLayout.addWidget(self.label_volume_title)
        self.tabwidget_volume = QtWidgets.QWidget(self.frame_volume)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabwidget_volume.sizePolicy().hasHeightForWidth())
        self.tabwidget_volume.setSizePolicy(sizePolicy)
        self.tabwidget_volume.setObjectName("tabwidget_volume")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tabwidget_volume)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.lineEdit_slice_distance = QtWidgets.QLineEdit(self.tabwidget_volume)
        self.lineEdit_slice_distance.setObjectName("lineEdit_slice_distance")
        self.gridLayout_19.addWidget(self.lineEdit_slice_distance, 4, 1, 1, 1)
        self.label_slice_number = QtWidgets.QLabel(self.tabwidget_volume)
        self.label_slice_number.setObjectName("label_slice_number")
        self.gridLayout_19.addWidget(self.label_slice_number, 5, 0, 1, 1)
        self.lineEdit_slice_number = QtWidgets.QLineEdit(self.tabwidget_volume)
        self.lineEdit_slice_number.setObjectName("lineEdit_slice_number")
        self.gridLayout_19.addWidget(self.lineEdit_slice_number, 5, 1, 1, 1)
        self.label_slice_distance = QtWidgets.QLabel(self.tabwidget_volume)
        self.label_slice_distance.setObjectName("label_slice_distance")
        self.gridLayout_19.addWidget(self.label_slice_distance, 4, 0, 1, 1)
        self.widget_laser3 = QtWidgets.QWidget(self.tabwidget_volume)
        self.widget_laser3.setObjectName("widget_laser3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_laser3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_exposure_3 = QtWidgets.QLineEdit(self.widget_laser3)
        self.lineEdit_exposure_3.setEnabled(False)
        self.lineEdit_exposure_3.setObjectName("lineEdit_exposure_3")
        self.gridLayout_10.addWidget(self.lineEdit_exposure_3, 0, 2, 1, 1)
        self.checkBox_laser3 = QtWidgets.QCheckBox(self.widget_laser3)
        self.checkBox_laser3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser3.setObjectName("checkBox_laser3")
        self.gridLayout_10.addWidget(self.checkBox_laser3, 0, 0, 1, 1)
        self.spinBox_laser3 = QtWidgets.QSpinBox(self.widget_laser3)
        self.spinBox_laser3.setEnabled(False)
        self.spinBox_laser3.setObjectName("spinBox_laser3")
        self.gridLayout_10.addWidget(self.spinBox_laser3, 2, 0, 1, 1)
        self.label_exposure_4 = QtWidgets.QLabel(self.widget_laser3)
        self.label_exposure_4.setObjectName("label_exposure_4")
        self.gridLayout_10.addWidget(self.label_exposure_4, 0, 1, 1, 1)
        self.slider_laser3 = QtWidgets.QSlider(self.widget_laser3)
        self.slider_laser3.setEnabled(False)
        self.slider_laser3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_laser3.setObjectName("slider_laser3")
        self.gridLayout_10.addWidget(self.slider_laser3, 2, 1, 1, 2)
        self.gridLayout_19.addWidget(self.widget_laser3, 2, 0, 1, 2)
        self.widget_laser4 = QtWidgets.QWidget(self.tabwidget_volume)
        self.widget_laser4.setObjectName("widget_laser4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_laser4)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_exposure_4 = QtWidgets.QLineEdit(self.widget_laser4)
        self.lineEdit_exposure_4.setEnabled(False)
        self.lineEdit_exposure_4.setObjectName("lineEdit_exposure_4")
        self.gridLayout_11.addWidget(self.lineEdit_exposure_4, 0, 2, 1, 1)
        self.checkBox_laser4 = QtWidgets.QCheckBox(self.widget_laser4)
        self.checkBox_laser4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser4.setObjectName("checkBox_laser4")
        self.gridLayout_11.addWidget(self.checkBox_laser4, 0, 0, 1, 1)
        self.spinBox_laser4 = QtWidgets.QSpinBox(self.widget_laser4)
        self.spinBox_laser4.setEnabled(False)
        self.spinBox_laser4.setObjectName("spinBox_laser4")
        self.gridLayout_11.addWidget(self.spinBox_laser4, 1, 0, 1, 1)
        self.label_exposure_5 = QtWidgets.QLabel(self.widget_laser4)
        self.label_exposure_5.setObjectName("label_exposure_5")
        self.gridLayout_11.addWidget(self.label_exposure_5, 0, 1, 1, 1)
        self.slider_laser4 = QtWidgets.QSlider(self.widget_laser4)
        self.slider_laser4.setEnabled(False)
        self.slider_laser4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_laser4.setObjectName("slider_laser4")
        self.gridLayout_11.addWidget(self.slider_laser4, 1, 1, 1, 2)
        self.gridLayout_19.addWidget(self.widget_laser4, 3, 0, 1, 2)
        self.widget_laser1 = QtWidgets.QWidget(self.tabwidget_volume)
        self.widget_laser1.setObjectName("widget_laser1")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_laser1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_exposure_2 = QtWidgets.QLabel(self.widget_laser1)
        self.label_exposure_2.setObjectName("label_exposure_2")
        self.gridLayout_8.addWidget(self.label_exposure_2, 0, 1, 1, 1)
        self.slider_laser1 = QtWidgets.QSlider(self.widget_laser1)
        self.slider_laser1.setEnabled(False)
        self.slider_laser1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_laser1.setObjectName("slider_laser1")
        self.gridLayout_8.addWidget(self.slider_laser1, 1, 1, 1, 4)
        self.checkBox_laser1 = QtWidgets.QCheckBox(self.widget_laser1)
        self.checkBox_laser1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser1.setObjectName("checkBox_laser1")
        self.gridLayout_8.addWidget(self.checkBox_laser1, 0, 0, 1, 1)
        self.spinBox_laser1 = QtWidgets.QSpinBox(self.widget_laser1)
        self.spinBox_laser1.setEnabled(False)
        self.spinBox_laser1.setObjectName("spinBox_laser1")
        self.gridLayout_8.addWidget(self.spinBox_laser1, 1, 0, 1, 1)
        self.lineEdit_exposure_1 = QtWidgets.QLineEdit(self.widget_laser1)
        self.lineEdit_exposure_1.setEnabled(False)
        self.lineEdit_exposure_1.setObjectName("lineEdit_exposure_1")
        self.gridLayout_8.addWidget(self.lineEdit_exposure_1, 0, 2, 1, 3)
        self.gridLayout_19.addWidget(self.widget_laser1, 0, 0, 1, 2)
        self.widget_laser2 = QtWidgets.QWidget(self.tabwidget_volume)
        self.widget_laser2.setObjectName("widget_laser2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_laser2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.checkBox_laser2 = QtWidgets.QCheckBox(self.widget_laser2)
        self.checkBox_laser2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser2.setObjectName("checkBox_laser2")
        self.gridLayout_9.addWidget(self.checkBox_laser2, 0, 0, 1, 1)
        self.spinBox_laser2 = QtWidgets.QSpinBox(self.widget_laser2)
        self.spinBox_laser2.setEnabled(False)
        self.spinBox_laser2.setObjectName("spinBox_laser2")
        self.gridLayout_9.addWidget(self.spinBox_laser2, 2, 0, 1, 1)
        self.lineEdit_exposure_2 = QtWidgets.QLineEdit(self.widget_laser2)
        self.lineEdit_exposure_2.setEnabled(False)
        self.lineEdit_exposure_2.setObjectName("lineEdit_exposure_2")
        self.gridLayout_9.addWidget(self.lineEdit_exposure_2, 0, 2, 1, 1)
        self.label_exposure_3 = QtWidgets.QLabel(self.widget_laser2)
        self.label_exposure_3.setObjectName("label_exposure_3")
        self.gridLayout_9.addWidget(self.label_exposure_3, 0, 1, 1, 1)
        self.slider_laser2 = QtWidgets.QSlider(self.widget_laser2)
        self.slider_laser2.setEnabled(False)
        self.slider_laser2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_laser2.setObjectName("slider_laser2")
        self.gridLayout_9.addWidget(self.slider_laser2, 2, 1, 1, 2)
        self.gridLayout_19.addWidget(self.widget_laser2, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.tabwidget_volume)
        self.frame_buttons_extra = QtWidgets.QFrame(self.frame_volume)
        self.frame_buttons_extra.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_extra.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_extra.setObjectName("frame_buttons_extra")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_buttons_extra)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_buttons_extra)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 8, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 1, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 7, 0, 1, 2)
        self.pushButton_initialise_stage = QtWidgets.QPushButton(self.frame_buttons_extra)
        self.pushButton_initialise_stage.setObjectName("pushButton_initialise_stage")
        self.gridLayout_6.addWidget(self.pushButton_initialise_stage, 10, 0, 1, 2)
        self.pushButton_move_relative = QtWidgets.QPushButton(self.frame_buttons_extra)
        self.pushButton_move_relative.setObjectName("pushButton_move_relative")
        self.gridLayout_6.addWidget(self.pushButton_move_relative, 12, 0, 1, 1)
        self.to_electron_microscope = QtWidgets.QPushButton(self.frame_buttons_extra)
        self.to_electron_microscope.setObjectName("to_electron_microscope")
        self.gridLayout_6.addWidget(self.to_electron_microscope, 5, 1, 1, 1)
        self.pushButton_move_absolute = QtWidgets.QPushButton(self.frame_buttons_extra)
        self.pushButton_move_absolute.setObjectName("pushButton_move_absolute")
        self.gridLayout_6.addWidget(self.pushButton_move_absolute, 11, 0, 1, 1)
        self.connect_microscope = QtWidgets.QPushButton(self.frame_buttons_extra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_microscope.sizePolicy().hasHeightForWidth())
        self.connect_microscope.setSizePolicy(sizePolicy)
        self.connect_microscope.setObjectName("connect_microscope")
        self.gridLayout_6.addWidget(self.connect_microscope, 6, 0, 1, 2)
        self.lineEdit_move_absolute = QtWidgets.QLineEdit(self.frame_buttons_extra)
        self.lineEdit_move_absolute.setObjectName("lineEdit_move_absolute")
        self.gridLayout_6.addWidget(self.lineEdit_move_absolute, 11, 1, 1, 1)
        self.to_light_microscope = QtWidgets.QPushButton(self.frame_buttons_extra)
        self.to_light_microscope.setObjectName("to_light_microscope")
        self.gridLayout_6.addWidget(self.to_light_microscope, 5, 0, 1, 1)
        self.lineEdit_move_relative = QtWidgets.QLineEdit(self.frame_buttons_extra)
        self.lineEdit_move_relative.setObjectName("lineEdit_move_relative")
        self.gridLayout_6.addWidget(self.lineEdit_move_relative, 12, 1, 1, 1)
        self.pushButton_volume = QtWidgets.QPushButton(self.frame_buttons_extra)
        self.pushButton_volume.setFlat(False)
        self.pushButton_volume.setObjectName("pushButton_volume")
        self.gridLayout_6.addWidget(self.pushButton_volume, 0, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.frame_buttons_extra)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.toolButton_correlation_output = QtWidgets.QToolButton(self.frame)
        self.toolButton_correlation_output.setObjectName("toolButton_correlation_output")
        self.gridLayout_16.addWidget(self.toolButton_correlation_output, 2, 1, 1, 1)
        self.pushButton_correlation = QtWidgets.QPushButton(self.frame)
        self.pushButton_correlation.setObjectName("pushButton_correlation")
        self.gridLayout_16.addWidget(self.pushButton_correlation, 1, 0, 1, 2)
        self.correlation_output_path = QtWidgets.QLineEdit(self.frame)
        self.correlation_output_path.setObjectName("correlation_output_path")
        self.gridLayout_16.addWidget(self.correlation_output_path, 2, 0, 1, 1)
        self.pushButton_milling = QtWidgets.QPushButton(self.frame)
        self.pushButton_milling.setObjectName("pushButton_milling")
        self.gridLayout_16.addWidget(self.pushButton_milling, 3, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame, 2, 0, 1, 2)
        self.label_objective_stage_position = QtWidgets.QLabel(self.frame_buttons_extra)
        self.label_objective_stage_position.setText("")
        self.label_objective_stage_position.setObjectName("label_objective_stage_position")
        self.gridLayout_6.addWidget(self.label_objective_stage_position, 8, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_buttons_extra)
        self.horizontalLayout.addWidget(self.frame_volume)
        self.line = QtWidgets.QFrame(self.Main_Frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.frame_fluorescence = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_fluorescence.sizePolicy().hasHeightForWidth())
        self.frame_fluorescence.setSizePolicy(sizePolicy)
        self.frame_fluorescence.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_fluorescence.setMaximumSize(QtCore.QSize(980, 914))
        self.frame_fluorescence.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fluorescence.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fluorescence.setObjectName("frame_fluorescence")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_fluorescence)
        self.gridLayout_4.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 5, 0, 1, 1)
        self.frame_save_destination_FM = QtWidgets.QFrame(self.frame_fluorescence)
        self.frame_save_destination_FM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_save_destination_FM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_save_destination_FM.setObjectName("frame_save_destination_FM")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_save_destination_FM)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_save_destination_FM = QtWidgets.QLabel(self.frame_save_destination_FM)
        self.label_save_destination_FM.setObjectName("label_save_destination_FM")
        self.gridLayout_3.addWidget(self.label_save_destination_FM, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 0, 1, 1)
        self.lineEdit_save_filename_FM = QtWidgets.QLineEdit(self.frame_save_destination_FM)
        self.lineEdit_save_filename_FM.setObjectName("lineEdit_save_filename_FM")
        self.gridLayout_3.addWidget(self.lineEdit_save_filename_FM, 4, 1, 1, 3)
        self.checkBox_save_destination_FM = QtWidgets.QCheckBox(self.frame_save_destination_FM)
        self.checkBox_save_destination_FM.setMinimumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination_FM.setMaximumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination_FM.setObjectName("checkBox_save_destination_FM")
        self.gridLayout_3.addWidget(self.checkBox_save_destination_FM, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 2, 4, 1, 1)
        self.button_save_destination_FM = QtWidgets.QToolButton(self.frame_save_destination_FM)
        self.button_save_destination_FM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_save_destination_FM.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.button_save_destination_FM.setObjectName("button_save_destination_FM")
        self.gridLayout_3.addWidget(self.button_save_destination_FM, 2, 3, 1, 1)
        self.label_save_filename_FM = QtWidgets.QLabel(self.frame_save_destination_FM)
        self.label_save_filename_FM.setObjectName("label_save_filename_FM")
        self.gridLayout_3.addWidget(self.label_save_filename_FM, 3, 1, 1, 1)
        self.lineEdit_save_destination_FM = QtWidgets.QLineEdit(self.frame_save_destination_FM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_save_destination_FM.sizePolicy().hasHeightForWidth())
        self.lineEdit_save_destination_FM.setSizePolicy(sizePolicy)
        self.lineEdit_save_destination_FM.setMinimumSize(QtCore.QSize(480, 20))
        self.lineEdit_save_destination_FM.setMaximumSize(QtCore.QSize(12356345, 345345))
        self.lineEdit_save_destination_FM.setObjectName("lineEdit_save_destination_FM")
        self.gridLayout_3.addWidget(self.lineEdit_save_destination_FM, 2, 1, 1, 2)
        self.label_FM = QtWidgets.QLabel(self.frame_save_destination_FM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FM.sizePolicy().hasHeightForWidth())
        self.label_FM.setSizePolicy(sizePolicy)
        self.label_FM.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FM.setObjectName("label_FM")
        self.gridLayout_3.addWidget(self.label_FM, 0, 1, 1, 3)
        self.gridLayout_4.addWidget(self.frame_save_destination_FM, 0, 0, 1, 1)
        self.frame_label_fluorescence = QtWidgets.QFrame(self.frame_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_fluorescence.sizePolicy().hasHeightForWidth())
        self.frame_label_fluorescence.setSizePolicy(sizePolicy)
        self.frame_label_fluorescence.setMinimumSize(QtCore.QSize(640, 400))
        self.frame_label_fluorescence.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_fluorescence.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_fluorescence.setObjectName("frame_label_fluorescence")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_label_fluorescence)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_image_FM = QtWidgets.QLabel(self.frame_label_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_FM.sizePolicy().hasHeightForWidth())
        self.label_image_FM.setSizePolicy(sizePolicy)
        self.label_image_FM.setMinimumSize(QtCore.QSize(0, 0))
        self.label_image_FM.setMaximumSize(QtCore.QSize(650, 410))
        self.label_image_FM.setText("")
        self.label_image_FM.setObjectName("label_image_FM")
        self.gridLayout_17.addWidget(self.label_image_FM, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_4.addWidget(self.frame_label_fluorescence, 1, 0, 1, 1)
        self.frame_buttons_FM = QtWidgets.QFrame(self.frame_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons_FM.sizePolicy().hasHeightForWidth())
        self.frame_buttons_FM.setSizePolicy(sizePolicy)
        self.frame_buttons_FM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_FM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_FM.setObjectName("frame_buttons_FM")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_buttons_FM)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setSpacing(4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem5, 4, 7, 1, 1)
        self.comboBox_laser_basler = QtWidgets.QComboBox(self.frame_buttons_FM)
        self.comboBox_laser_basler.setEditable(False)
        self.comboBox_laser_basler.setObjectName("comboBox_laser_basler")
        self.comboBox_laser_basler.addItem("")
        self.comboBox_laser_basler.addItem("")
        self.comboBox_laser_basler.addItem("")
        self.comboBox_laser_basler.addItem("")
        self.gridLayout_18.addWidget(self.comboBox_laser_basler, 4, 1, 1, 1)
        self.lineEdit_power_basler_2 = QtWidgets.QLineEdit(self.frame_buttons_FM)
        self.lineEdit_power_basler_2.setObjectName("lineEdit_power_basler_2")
        self.gridLayout_18.addWidget(self.lineEdit_power_basler_2, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_buttons_FM)
        self.label_2.setObjectName("label_2")
        self.gridLayout_18.addWidget(self.label_2, 4, 2, 1, 1)
        self.lineEdit_exposure_basler = QtWidgets.QLineEdit(self.frame_buttons_FM)
        self.lineEdit_exposure_basler.setObjectName("lineEdit_exposure_basler")
        self.gridLayout_18.addWidget(self.lineEdit_exposure_basler, 4, 6, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_buttons_FM)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 4, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem6, 4, 0, 1, 1)
        self.button_live_image_FM = QtWidgets.QPushButton(self.frame_buttons_FM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_live_image_FM.sizePolicy().hasHeightForWidth())
        self.button_live_image_FM.setSizePolicy(sizePolicy)
        self.button_live_image_FM.setMinimumSize(QtCore.QSize(100, 0))
        self.button_live_image_FM.setObjectName("button_live_image_FM")
        self.gridLayout_18.addWidget(self.button_live_image_FM, 3, 5, 1, 2)
        self.button_get_image_FM = QtWidgets.QPushButton(self.frame_buttons_FM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_FM.sizePolicy().hasHeightForWidth())
        self.button_get_image_FM.setSizePolicy(sizePolicy)
        self.button_get_image_FM.setMinimumSize(QtCore.QSize(100, 0))
        self.button_get_image_FM.setObjectName("button_get_image_FM")
        self.gridLayout_18.addWidget(self.button_get_image_FM, 3, 2, 1, 3)
        self.gridLayout_4.addWidget(self.frame_buttons_FM, 4, 0, 1, 1)
        self.frame_slider_FM = QtWidgets.QFrame(self.frame_fluorescence)
        self.frame_slider_FM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slider_FM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slider_FM.setObjectName("frame_slider_FM")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_slider_FM)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layout_image_vertical = QtWidgets.QVBoxLayout()
        self.layout_image_vertical.setObjectName("layout_image_vertical")
        self.layout_image_horizontal = QtWidgets.QHBoxLayout()
        self.layout_image_horizontal.setObjectName("layout_image_horizontal")
        self.label_slider_FM = QtWidgets.QLabel(self.frame_slider_FM)
        self.label_slider_FM.setObjectName("label_slider_FM")
        self.layout_image_horizontal.addWidget(self.label_slider_FM)
        spacerItem7 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_image_horizontal.addItem(spacerItem7)
        self.spinbox_slider_FM = QtWidgets.QSpinBox(self.frame_slider_FM)
        self.spinbox_slider_FM.setMinimumSize(QtCore.QSize(37, 20))
        self.spinbox_slider_FM.setMaximumSize(QtCore.QSize(37, 20))
        self.spinbox_slider_FM.setMinimum(1)
        self.spinbox_slider_FM.setMaximum(1)
        self.spinbox_slider_FM.setProperty("value", 1)
        self.spinbox_slider_FM.setObjectName("spinbox_slider_FM")
        self.layout_image_horizontal.addWidget(self.spinbox_slider_FM)
        self.layout_image_vertical.addLayout(self.layout_image_horizontal)
        self.slider_stack_FM = QtWidgets.QSlider(self.frame_slider_FM)
        self.slider_stack_FM.setMinimum(1)
        self.slider_stack_FM.setMaximum(1)
        self.slider_stack_FM.setSingleStep(1)
        self.slider_stack_FM.setProperty("value", 1)
        self.slider_stack_FM.setOrientation(QtCore.Qt.Horizontal)
        self.slider_stack_FM.setObjectName("slider_stack_FM")
        self.layout_image_vertical.addWidget(self.slider_stack_FM)
        self.gridLayout_2.addLayout(self.layout_image_vertical, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_slider_FM, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_fluorescence)
        self.line_2 = QtWidgets.QFrame(self.Main_Frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.frame_FIBSEM = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_FIBSEM.setAutoFillBackground(False)
        self.frame_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_FIBSEM.setObjectName("frame_FIBSEM")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_FIBSEM)
        self.gridLayout.setContentsMargins(9, 0, 9, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_slider_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_slider_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_slider_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_slider_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slider_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slider_FIBSEM.setObjectName("frame_slider_FIBSEM")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_slider_FIBSEM)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.layout_image_vertical_2 = QtWidgets.QVBoxLayout()
        self.layout_image_vertical_2.setObjectName("layout_image_vertical_2")
        self.layout_image_horizontal_2 = QtWidgets.QHBoxLayout()
        self.layout_image_horizontal_2.setObjectName("layout_image_horizontal_2")
        self.label_slider_2 = QtWidgets.QLabel(self.frame_slider_FIBSEM)
        self.label_slider_2.setObjectName("label_slider_2")
        self.layout_image_horizontal_2.addWidget(self.label_slider_2)
        spacerItem10 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.layout_image_horizontal_2.addItem(spacerItem10)
        self.spinbox_slider_FIBSEM = QtWidgets.QSpinBox(self.frame_slider_FIBSEM)
        self.spinbox_slider_FIBSEM.setMinimumSize(QtCore.QSize(37, 20))
        self.spinbox_slider_FIBSEM.setMaximumSize(QtCore.QSize(37, 20))
        self.spinbox_slider_FIBSEM.setMinimum(1)
        self.spinbox_slider_FIBSEM.setMaximum(1)
        self.spinbox_slider_FIBSEM.setProperty("value", 1)
        self.spinbox_slider_FIBSEM.setObjectName("spinbox_slider_FIBSEM")
        self.layout_image_horizontal_2.addWidget(self.spinbox_slider_FIBSEM)
        self.layout_image_vertical_2.addLayout(self.layout_image_horizontal_2)
        self.slider_stack_FIBSEM = QtWidgets.QSlider(self.frame_slider_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_stack_FIBSEM.sizePolicy().hasHeightForWidth())
        self.slider_stack_FIBSEM.setSizePolicy(sizePolicy)
        self.slider_stack_FIBSEM.setMinimum(1)
        self.slider_stack_FIBSEM.setMaximum(1)
        self.slider_stack_FIBSEM.setSingleStep(1)
        self.slider_stack_FIBSEM.setProperty("value", 1)
        self.slider_stack_FIBSEM.setOrientation(QtCore.Qt.Horizontal)
        self.slider_stack_FIBSEM.setObjectName("slider_stack_FIBSEM")
        self.layout_image_vertical_2.addWidget(self.slider_stack_FIBSEM)
        self.gridLayout_12.addLayout(self.layout_image_vertical_2, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem11, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem12, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.frame_slider_FIBSEM, 3, 0, 1, 1)
        self.frame_label_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_label_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_label_FIBSEM.setMinimumSize(QtCore.QSize(640, 400))
        self.frame_label_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_FIBSEM.setObjectName("frame_label_FIBSEM")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_label_FIBSEM)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_image_FIBSEM = QtWidgets.QLabel(self.frame_label_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_FIBSEM.sizePolicy().hasHeightForWidth())
        self.label_image_FIBSEM.setSizePolicy(sizePolicy)
        self.label_image_FIBSEM.setMaximumSize(QtCore.QSize(640, 400))
        self.label_image_FIBSEM.setText("")
        self.label_image_FIBSEM.setObjectName("label_image_FIBSEM")
        self.gridLayout_14.addWidget(self.label_image_FIBSEM, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.frame_label_FIBSEM, 2, 0, 1, 2)
        self.frame_save_destination_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_save_destination_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_save_destination_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_save_destination_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_save_destination_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_save_destination_FIBSEM.setObjectName("frame_save_destination_FIBSEM")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_save_destination_FIBSEM)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem13, 2, 5, 1, 1)
        self.lineEdit_save_destination_FIBSEM = QtWidgets.QLineEdit(self.frame_save_destination_FIBSEM)
        self.lineEdit_save_destination_FIBSEM.setMinimumSize(QtCore.QSize(480, 20))
        self.lineEdit_save_destination_FIBSEM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_save_destination_FIBSEM.setObjectName("lineEdit_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.lineEdit_save_destination_FIBSEM, 2, 1, 1, 3)
        self.checkBox_save_destination_FIBSEM = QtWidgets.QCheckBox(self.frame_save_destination_FIBSEM)
        self.checkBox_save_destination_FIBSEM.setMinimumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination_FIBSEM.setMaximumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination_FIBSEM.setObjectName("checkBox_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.checkBox_save_destination_FIBSEM, 1, 3, 1, 1)
        self.button_save_destination_FIBSEM = QtWidgets.QToolButton(self.frame_save_destination_FIBSEM)
        self.button_save_destination_FIBSEM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_save_destination_FIBSEM.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.button_save_destination_FIBSEM.setObjectName("button_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.button_save_destination_FIBSEM, 2, 4, 1, 1)
        self.label_save_filename_FIBSEM = QtWidgets.QLabel(self.frame_save_destination_FIBSEM)
        self.label_save_filename_FIBSEM.setObjectName("label_save_filename_FIBSEM")
        self.gridLayout_7.addWidget(self.label_save_filename_FIBSEM, 3, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem14, 2, 0, 1, 1)
        self.label_save_destination_FIBSEM = QtWidgets.QLabel(self.frame_save_destination_FIBSEM)
        self.label_save_destination_FIBSEM.setObjectName("label_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.label_save_destination_FIBSEM, 1, 1, 1, 1)
        self.lineEdit_save_filename_FIBSEM = QtWidgets.QLineEdit(self.frame_save_destination_FIBSEM)
        self.lineEdit_save_filename_FIBSEM.setObjectName("lineEdit_save_filename_FIBSEM")
        self.gridLayout_7.addWidget(self.lineEdit_save_filename_FIBSEM, 4, 1, 1, 4)
        self.label_FIBSEM = QtWidgets.QLabel(self.frame_save_destination_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FIBSEM.sizePolicy().hasHeightForWidth())
        self.label_FIBSEM.setSizePolicy(sizePolicy)
        self.label_FIBSEM.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_FIBSEM.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FIBSEM.setObjectName("label_FIBSEM")
        self.gridLayout_7.addWidget(self.label_FIBSEM, 0, 1, 1, 4)
        self.gridLayout.addWidget(self.frame_save_destination_FIBSEM, 1, 0, 1, 2)
        self.frame_buttons_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_buttons_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_buttons_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_FIBSEM.setObjectName("frame_buttons_FIBSEM")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_buttons_FIBSEM)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_2 = QtWidgets.QFrame(self.frame_buttons_FIBSEM)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.button_get_image_FIB = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_FIB.sizePolicy().hasHeightForWidth())
        self.button_get_image_FIB.setSizePolicy(sizePolicy)
        self.button_get_image_FIB.setObjectName("button_get_image_FIB")
        self.gridLayout_13.addWidget(self.button_get_image_FIB, 0, 0, 1, 1)
        self.button_get_image_SEM = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_SEM.sizePolicy().hasHeightForWidth())
        self.button_get_image_SEM.setSizePolicy(sizePolicy)
        self.button_get_image_SEM.setObjectName("button_get_image_SEM")
        self.gridLayout_13.addWidget(self.button_get_image_SEM, 0, 1, 1, 1)
        self.button_last_image_FIB = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_last_image_FIB.sizePolicy().hasHeightForWidth())
        self.button_last_image_FIB.setSizePolicy(sizePolicy)
        self.button_last_image_FIB.setObjectName("button_last_image_FIB")
        self.gridLayout_13.addWidget(self.button_last_image_FIB, 1, 0, 1, 1)
        self.button_last_image_SEM = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_last_image_SEM.sizePolicy().hasHeightForWidth())
        self.button_last_image_SEM.setSizePolicy(sizePolicy)
        self.button_last_image_SEM.setObjectName("button_last_image_SEM")
        self.gridLayout_13.addWidget(self.button_last_image_SEM, 1, 1, 1, 1)
        self.gridLayout_20.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_buttons_FIBSEM)
        self.frame_3.setMaximumSize(QtCore.QSize(245, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.comboBox_resolution = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_resolution.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_resolution.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_resolution.setObjectName("comboBox_resolution")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_resolution, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_15.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_dwell_time = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_dwell_time.setMaximumSize(QtCore.QSize(65, 16777215))
        self.lineEdit_dwell_time.setObjectName("lineEdit_dwell_time")
        self.gridLayout_15.addWidget(self.lineEdit_dwell_time, 0, 1, 1, 1)
        self.checkBox_Autocontrast = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_Autocontrast.setMinimumSize(QtCore.QSize(90, 0))
        self.checkBox_Autocontrast.setObjectName("checkBox_Autocontrast")
        self.gridLayout_15.addWidget(self.checkBox_Autocontrast, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 1, 0, 1, 1)
        self.gridLayout_20.addWidget(self.frame_3, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_buttons_FIBSEM, 4, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_FIBSEM)
        self.gridLayout_5.addWidget(self.Main_Frame, 0, 0, 1, 1)
        MainGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1623, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menuFile)
        self.menuHelp.setObjectName("menuHelp")
        MainGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainGui)
        self.statusbar.setObjectName("statusbar")
        MainGui.setStatusBar(self.statusbar)
        self.actionOpen_FM_Image = QtWidgets.QAction(MainGui)
        self.actionOpen_FM_Image.setObjectName("actionOpen_FM_Image")
        self.actionOpen_FIBSEM_Image = QtWidgets.QAction(MainGui)
        self.actionOpen_FIBSEM_Image.setObjectName("actionOpen_FIBSEM_Image")
        self.actionSave_FM_Image = QtWidgets.QAction(MainGui)
        self.actionSave_FM_Image.setObjectName("actionSave_FM_Image")
        self.actionSave_FIBSEM_Image = QtWidgets.QAction(MainGui)
        self.actionSave_FIBSEM_Image.setObjectName("actionSave_FIBSEM_Image")
        self.actionAbout = QtWidgets.QAction(MainGui)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOpen.addAction(self.actionOpen_FM_Image)
        self.menuOpen.addAction(self.actionOpen_FIBSEM_Image)
        self.menuSave.addAction(self.actionSave_FM_Image)
        self.menuSave.addAction(self.actionSave_FIBSEM_Image)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainGui)
        self.spinbox_slider_FM.valueChanged['int'].connect(self.slider_stack_FM.setValue)
        self.slider_stack_FM.valueChanged['int'].connect(self.spinbox_slider_FM.setValue)
        self.slider_stack_FIBSEM.valueChanged['int'].connect(self.spinbox_slider_FIBSEM.setValue)
        self.spinbox_slider_FIBSEM.valueChanged['int'].connect(self.slider_stack_FIBSEM.setValue)
        self.slider_laser1.valueChanged['int'].connect(self.spinBox_laser1.setValue)
        self.spinBox_laser1.valueChanged['int'].connect(self.slider_laser1.setValue)
        self.slider_laser2.valueChanged['int'].connect(self.spinBox_laser2.setValue)
        self.spinBox_laser2.valueChanged['int'].connect(self.slider_laser2.setValue)
        self.spinBox_laser3.valueChanged['int'].connect(self.slider_laser3.setValue)
        self.slider_laser3.valueChanged['int'].connect(self.spinBox_laser3.setValue)
        self.spinBox_laser4.valueChanged['int'].connect(self.slider_laser4.setValue)
        self.slider_laser4.valueChanged['int'].connect(self.spinBox_laser4.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainGui)

    def retranslateUi(self, MainGui):
        _translate = QtCore.QCoreApplication.translate
        MainGui.setWindowTitle(_translate("MainGui", "MainWindow"))
        self.label_volume_title.setText(_translate("MainGui", "Volume Acquisition"))
        self.label_slice_number.setText(_translate("MainGui", "Number of Slices"))
        self.label_slice_distance.setText(_translate("MainGui", "Slice Distance (nm)"))
        self.lineEdit_exposure_3.setText(_translate("MainGui", "1000"))
        self.checkBox_laser3.setText(_translate("MainGui", "488nm"))
        self.label_exposure_4.setText(_translate("MainGui", "Exposure (ms)"))
        self.lineEdit_exposure_4.setText(_translate("MainGui", "1000"))
        self.checkBox_laser4.setText(_translate("MainGui", "405nm"))
        self.label_exposure_5.setText(_translate("MainGui", "Exposure (ms)"))
        self.label_exposure_2.setText(_translate("MainGui", "Exposure (ms)"))
        self.checkBox_laser1.setText(_translate("MainGui", "640nm"))
        self.lineEdit_exposure_1.setText(_translate("MainGui", "1000"))
        self.checkBox_laser2.setText(_translate("MainGui", "561nm"))
        self.lineEdit_exposure_2.setText(_translate("MainGui", "1000"))
        self.label_exposure_3.setText(_translate("MainGui", "Exposure (ms)"))
        self.label_5.setText(_translate("MainGui", "Absolute Position:"))
        self.pushButton_initialise_stage.setText(_translate("MainGui", "Initialise Stage"))
        self.pushButton_move_relative.setText(_translate("MainGui", "Move Relative (um)"))
        self.to_electron_microscope.setText(_translate("MainGui", "To Electron Microscope"))
        self.pushButton_move_absolute.setText(_translate("MainGui", "Move Absolute (um)"))
        self.connect_microscope.setText(_translate("MainGui", "Connect to microscope"))
        self.to_light_microscope.setText(_translate("MainGui", "To Light Microscope"))
        self.pushButton_volume.setText(_translate("MainGui", "Acquire Volume"))
        self.toolButton_correlation_output.setText(_translate("MainGui", "..."))
        self.pushButton_correlation.setText(_translate("MainGui", "Correlation"))
        self.pushButton_milling.setText(_translate("MainGui", "Milling"))
        self.label_save_destination_FM.setText(_translate("MainGui", "Save Destination"))
        self.checkBox_save_destination_FM.setText(_translate("MainGui", "Lock Save Destination"))
        self.button_save_destination_FM.setText(_translate("MainGui", "..."))
        self.label_save_filename_FM.setText(_translate("MainGui", "Save Filename"))
        self.label_FM.setText(_translate("MainGui", "FM"))
        self.comboBox_laser_basler.setCurrentText(_translate("MainGui", "640nm"))
        self.comboBox_laser_basler.setItemText(0, _translate("MainGui", "640nm"))
        self.comboBox_laser_basler.setItemText(1, _translate("MainGui", "561nm"))
        self.comboBox_laser_basler.setItemText(2, _translate("MainGui", "488nm"))
        self.comboBox_laser_basler.setItemText(3, _translate("MainGui", "405nm"))
        self.lineEdit_power_basler_2.setText(_translate("MainGui", "0"))
        self.label_2.setText(_translate("MainGui", "Power level:"))
        self.lineEdit_exposure_basler.setText(_translate("MainGui", "1000"))
        self.label.setText(_translate("MainGui", "Exposure (ms): "))
        self.button_live_image_FM.setText(_translate("MainGui", "Live Basler View"))
        self.button_get_image_FM.setText(_translate("MainGui", "Get Basler Image"))
        self.label_slider_FM.setText(_translate("MainGui", "Stack Slider"))
        self.label_slider_2.setText(_translate("MainGui", "Stack Slider"))
        self.checkBox_save_destination_FIBSEM.setText(_translate("MainGui", "Lock Save Destination"))
        self.button_save_destination_FIBSEM.setText(_translate("MainGui", "..."))
        self.label_save_filename_FIBSEM.setText(_translate("MainGui", "Save Filename"))
        self.label_save_destination_FIBSEM.setText(_translate("MainGui", "Save Destination"))
        self.label_FIBSEM.setText(_translate("MainGui", "FIBSEM"))
        self.button_get_image_FIB.setText(_translate("MainGui", "Get FIB Image"))
        self.button_get_image_SEM.setText(_translate("MainGui", "Get SEM Image"))
        self.button_last_image_FIB.setText(_translate("MainGui", "Grab Last FIB"))
        self.button_last_image_SEM.setText(_translate("MainGui", "Grab Last SEM"))
        self.comboBox_resolution.setItemText(0, _translate("MainGui", "768x512"))
        self.comboBox_resolution.setItemText(1, _translate("MainGui", "1536x1024"))
        self.comboBox_resolution.setItemText(2, _translate("MainGui", "3072x2048"))
        self.comboBox_resolution.setItemText(3, _translate("MainGui", "6144x4096"))
        self.label_3.setText(_translate("MainGui", "Dwell Time (us)"))
        self.lineEdit_dwell_time.setText(_translate("MainGui", "1"))
        self.checkBox_Autocontrast.setText(_translate("MainGui", "Autocontrast"))
        self.label_4.setText(_translate("MainGui", "Resolution"))
        self.menuFile.setTitle(_translate("MainGui", "File"))
        self.menuOpen.setTitle(_translate("MainGui", "Open"))
        self.menuSave.setTitle(_translate("MainGui", "Save"))
        self.menuHelp.setTitle(_translate("MainGui", "Help"))
        self.actionOpen_FM_Image.setText(_translate("MainGui", "Open FM Image"))
        self.actionOpen_FIBSEM_Image.setText(_translate("MainGui", "Open FIBSEM Image"))
        self.actionSave_FM_Image.setText(_translate("MainGui", "Save FM Image"))
        self.actionSave_FIBSEM_Image.setText(_translate("MainGui", "Save FIBSEM Image"))
        self.actionAbout.setText(_translate("MainGui", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainGui = QtWidgets.QMainWindow()
    ui = Ui_MainGui()
    ui.setupUi(MainGui)
    MainGui.show()
    sys.exit(app.exec_())
