# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainGui(object):
    def setupUi(self, MainGui):
        MainGui.setObjectName("MainGui")
        MainGui.resize(1623, 739)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainGui.sizePolicy().hasHeightForWidth())
        MainGui.setSizePolicy(sizePolicy)
        MainGui.setMinimumSize(QtCore.QSize(1623, 739))
        MainGui.setMaximumSize(QtCore.QSize(16777215, 739))
        self.centralwidget = QtWidgets.QWidget(MainGui)
        self.centralwidget.setMaximumSize(QtCore.QSize(1623, 698))
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Frame.setGeometry(QtCore.QRect(0, 0, 1611, 698))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_Frame.sizePolicy().hasHeightForWidth())
        self.Main_Frame.setSizePolicy(sizePolicy)
        self.Main_Frame.setMinimumSize(QtCore.QSize(1600, 698))
        self.Main_Frame.setMaximumSize(QtCore.QSize(1650, 698))
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Frame.setObjectName("Main_Frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Main_Frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_volume = QtWidgets.QFrame(self.Main_Frame)
        self.frame_volume.setMinimumSize(QtCore.QSize(271, 696))
        self.frame_volume.setMaximumSize(QtCore.QSize(271, 696))
        self.frame_volume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_volume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_volume.setObjectName("frame_volume")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_volume)
        self.verticalLayout.setContentsMargins(3, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_laser1 = QtWidgets.QWidget(self.frame_volume)
        self.widget_laser1.setObjectName("widget_laser1")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.widget_laser1)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.radioButton_640 = QtWidgets.QRadioButton(self.widget_laser1)
        self.radioButton_640.setText("")
        self.radioButton_640.setObjectName("radioButton_640")
        self.buttonGroup = QtWidgets.QButtonGroup(MainGui)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_640)
        self.gridLayout_24.addWidget(self.radioButton_640, 0, 3, 1, 1)
        self.spinBox_laser1 = QtWidgets.QSpinBox(self.widget_laser1)
        self.spinBox_laser1.setEnabled(False)
        self.spinBox_laser1.setObjectName("spinBox_laser1")
        self.gridLayout_24.addWidget(self.spinBox_laser1, 2, 0, 1, 1)
        self.label_exposure_8 = QtWidgets.QLabel(self.widget_laser1)
        self.label_exposure_8.setObjectName("label_exposure_8")
        self.gridLayout_24.addWidget(self.label_exposure_8, 0, 1, 1, 1)
        self.slider_laser1 = QtWidgets.QSlider(self.widget_laser1)
        self.slider_laser1.setEnabled(False)
        self.slider_laser1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_laser1.setObjectName("slider_laser1")
        self.gridLayout_24.addWidget(self.slider_laser1, 2, 1, 1, 2)
        self.lineEdit_exposure_1 = QtWidgets.QLineEdit(self.widget_laser1)
        self.lineEdit_exposure_1.setEnabled(False)
        self.lineEdit_exposure_1.setObjectName("lineEdit_exposure_1")
        self.gridLayout_24.addWidget(self.lineEdit_exposure_1, 0, 2, 1, 1)
        self.checkBox_laser1 = QtWidgets.QCheckBox(self.widget_laser1)
        self.checkBox_laser1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser1.setObjectName("checkBox_laser1")
        self.gridLayout_24.addWidget(self.checkBox_laser1, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_laser1)
        self.widget_laser2 = QtWidgets.QWidget(self.frame_volume)
        self.widget_laser2.setObjectName("widget_laser2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.widget_laser2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.spinBox_laser2 = QtWidgets.QSpinBox(self.widget_laser2)
        self.spinBox_laser2.setEnabled(False)
        self.spinBox_laser2.setObjectName("spinBox_laser2")
        self.gridLayout_19.addWidget(self.spinBox_laser2, 2, 0, 1, 1)
        self.lineEdit_exposure_2 = QtWidgets.QLineEdit(self.widget_laser2)
        self.lineEdit_exposure_2.setEnabled(False)
        self.lineEdit_exposure_2.setObjectName("lineEdit_exposure_2")
        self.gridLayout_19.addWidget(self.lineEdit_exposure_2, 0, 2, 1, 1)
        self.label_exposure_6 = QtWidgets.QLabel(self.widget_laser2)
        self.label_exposure_6.setObjectName("label_exposure_6")
        self.gridLayout_19.addWidget(self.label_exposure_6, 0, 1, 1, 1)
        self.slider_laser2 = QtWidgets.QSlider(self.widget_laser2)
        self.slider_laser2.setEnabled(False)
        self.slider_laser2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_laser2.setObjectName("slider_laser2")
        self.gridLayout_19.addWidget(self.slider_laser2, 2, 1, 1, 2)
        self.checkBox_laser2 = QtWidgets.QCheckBox(self.widget_laser2)
        self.checkBox_laser2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser2.setObjectName("checkBox_laser2")
        self.gridLayout_19.addWidget(self.checkBox_laser2, 0, 0, 1, 1)
        self.radioButton_561 = QtWidgets.QRadioButton(self.widget_laser2)
        self.radioButton_561.setText("")
        self.radioButton_561.setObjectName("radioButton_561")
        self.buttonGroup.addButton(self.radioButton_561)
        self.gridLayout_19.addWidget(self.radioButton_561, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.widget_laser2)
        self.widget_laser3 = QtWidgets.QWidget(self.frame_volume)
        self.widget_laser3.setObjectName("widget_laser3")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.widget_laser3)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.spinBox_laser3 = QtWidgets.QSpinBox(self.widget_laser3)
        self.spinBox_laser3.setEnabled(False)
        self.spinBox_laser3.setObjectName("spinBox_laser3")
        self.gridLayout_23.addWidget(self.spinBox_laser3, 2, 0, 1, 1)
        self.lineEdit_exposure_3 = QtWidgets.QLineEdit(self.widget_laser3)
        self.lineEdit_exposure_3.setEnabled(False)
        self.lineEdit_exposure_3.setObjectName("lineEdit_exposure_3")
        self.gridLayout_23.addWidget(self.lineEdit_exposure_3, 0, 2, 1, 1)
        self.checkBox_laser3 = QtWidgets.QCheckBox(self.widget_laser3)
        self.checkBox_laser3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser3.setObjectName("checkBox_laser3")
        self.gridLayout_23.addWidget(self.checkBox_laser3, 0, 0, 1, 1)
        self.label_exposure_7 = QtWidgets.QLabel(self.widget_laser3)
        self.label_exposure_7.setObjectName("label_exposure_7")
        self.gridLayout_23.addWidget(self.label_exposure_7, 0, 1, 1, 1)
        self.slider_laser3 = QtWidgets.QSlider(self.widget_laser3)
        self.slider_laser3.setEnabled(False)
        self.slider_laser3.setOrientation(QtCore.Qt.Horizontal)
        self.slider_laser3.setObjectName("slider_laser3")
        self.gridLayout_23.addWidget(self.slider_laser3, 2, 1, 1, 2)
        self.radioButton_488 = QtWidgets.QRadioButton(self.widget_laser3)
        self.radioButton_488.setText("")
        self.radioButton_488.setChecked(True)
        self.radioButton_488.setObjectName("radioButton_488")
        self.buttonGroup.addButton(self.radioButton_488)
        self.gridLayout_23.addWidget(self.radioButton_488, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.widget_laser3)
        self.widget_laser4 = QtWidgets.QWidget(self.frame_volume)
        self.widget_laser4.setObjectName("widget_laser4")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.widget_laser4)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_exposure_9 = QtWidgets.QLabel(self.widget_laser4)
        self.label_exposure_9.setObjectName("label_exposure_9")
        self.gridLayout_25.addWidget(self.label_exposure_9, 1, 1, 1, 1)
        self.radioButton_405 = QtWidgets.QRadioButton(self.widget_laser4)
        self.radioButton_405.setText("")
        self.radioButton_405.setObjectName("radioButton_405")
        self.buttonGroup.addButton(self.radioButton_405)
        self.gridLayout_25.addWidget(self.radioButton_405, 1, 3, 1, 1)
        self.slider_laser4 = QtWidgets.QSlider(self.widget_laser4)
        self.slider_laser4.setEnabled(False)
        self.slider_laser4.setOrientation(QtCore.Qt.Horizontal)
        self.slider_laser4.setObjectName("slider_laser4")
        self.gridLayout_25.addWidget(self.slider_laser4, 2, 1, 1, 2)
        self.spinBox_laser4 = QtWidgets.QSpinBox(self.widget_laser4)
        self.spinBox_laser4.setEnabled(False)
        self.spinBox_laser4.setObjectName("spinBox_laser4")
        self.gridLayout_25.addWidget(self.spinBox_laser4, 2, 0, 1, 1)
        self.lineEdit_exposure_4 = QtWidgets.QLineEdit(self.widget_laser4)
        self.lineEdit_exposure_4.setEnabled(False)
        self.lineEdit_exposure_4.setObjectName("lineEdit_exposure_4")
        self.gridLayout_25.addWidget(self.lineEdit_exposure_4, 1, 2, 1, 1)
        self.checkBox_laser4 = QtWidgets.QCheckBox(self.widget_laser4)
        self.checkBox_laser4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser4.setObjectName("checkBox_laser4")
        self.gridLayout_25.addWidget(self.checkBox_laser4, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_laser4)
        self.frame_6 = QtWidgets.QFrame(self.frame_volume)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_volume_title = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_volume_title.sizePolicy().hasHeightForWidth())
        self.label_volume_title.setSizePolicy(sizePolicy)
        self.label_volume_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_volume_title.setObjectName("label_volume_title")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_volume_title)
        self.lineEdit_slice_distance = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_slice_distance.sizePolicy().hasHeightForWidth())
        self.lineEdit_slice_distance.setSizePolicy(sizePolicy)
        self.lineEdit_slice_distance.setObjectName("lineEdit_slice_distance")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_slice_distance)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.comboBox_2)
        self.lineEdit_volume_height = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_volume_height.setObjectName("lineEdit_volume_height")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_volume_height)
        self.pushButton_volume = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_volume.setFlat(False)
        self.pushButton_volume.setObjectName("pushButton_volume")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.pushButton_volume)
        self.comboBox = QtWidgets.QComboBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox.setMinimumContentsLength(23)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.comboBox)
        self.verticalLayout.addWidget(self.frame_6)
        self.d = QtWidgets.QTabWidget(self.frame_volume)
        self.d.setObjectName("d")
        self.sdfsd = QtWidgets.QWidget()
        self.sdfsd.setObjectName("sdfsd")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.sdfsd)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.frame_11 = QtWidgets.QFrame(self.sdfsd)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_27.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.pushButton_save_objective_position = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_save_objective_position.setObjectName("pushButton_save_objective_position")
        self.gridLayout_27.addWidget(self.pushButton_save_objective_position, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setObjectName("label_7")
        self.gridLayout_27.addWidget(self.label_7, 0, 0, 1, 1)
        self.pushButton_go_to_saved_position = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_go_to_saved_position.setObjectName("pushButton_go_to_saved_position")
        self.gridLayout_27.addWidget(self.pushButton_go_to_saved_position, 2, 1, 1, 1)
        self.pushButton_initialize_stage = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_initialize_stage.setObjectName("pushButton_initialize_stage")
        self.gridLayout_27.addWidget(self.pushButton_initialize_stage, 3, 1, 1, 1)
        self.pushButton_get_position = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_get_position.setObjectName("pushButton_get_position")
        self.gridLayout_27.addWidget(self.pushButton_get_position, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout_27.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_objective_stage_position = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_objective_stage_position.sizePolicy().hasHeightForWidth())
        self.label_objective_stage_position.setSizePolicy(sizePolicy)
        self.label_objective_stage_position.setText("")
        self.label_objective_stage_position.setObjectName("label_objective_stage_position")
        self.gridLayout_27.addWidget(self.label_objective_stage_position, 0, 1, 1, 1)
        self.label_objective_stage_saved_position = QtWidgets.QLabel(self.frame_11)
        self.label_objective_stage_saved_position.setMinimumSize(QtCore.QSize(0, 20))
        self.label_objective_stage_saved_position.setText("")
        self.label_objective_stage_saved_position.setObjectName("label_objective_stage_saved_position")
        self.gridLayout_27.addWidget(self.label_objective_stage_saved_position, 1, 1, 1, 1)
        self.gridLayout_26.addWidget(self.frame_11, 0, 0, 1, 2)
        self.frame_13 = QtWidgets.QFrame(self.sdfsd)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_29.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_29.setSpacing(6)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.toolButton_negative = QtWidgets.QToolButton(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_negative.sizePolicy().hasHeightForWidth())
        self.toolButton_negative.setSizePolicy(sizePolicy)
        self.toolButton_negative.setMinimumSize(QtCore.QSize(22, 22))
        self.toolButton_negative.setObjectName("toolButton_negative")
        self.gridLayout_29.addWidget(self.toolButton_negative, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_29.addItem(spacerItem, 3, 2, 1, 1)
        self.pushButton_move_absolute = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_move_absolute.setObjectName("pushButton_move_absolute")
        self.gridLayout_29.addWidget(self.pushButton_move_absolute, 1, 1, 1, 3)
        self.lineEdit_move_absolute = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_move_absolute.setObjectName("lineEdit_move_absolute")
        self.gridLayout_29.addWidget(self.lineEdit_move_absolute, 2, 2, 1, 1)
        self.pushButton_move_relative = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_move_relative.setObjectName("pushButton_move_relative")
        self.gridLayout_29.addWidget(self.pushButton_move_relative, 4, 1, 1, 3)
        self.lineEdit_move_relative = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_move_relative.setObjectName("lineEdit_move_relative")
        self.gridLayout_29.addWidget(self.lineEdit_move_relative, 5, 2, 1, 1)
        self.toolButton_positive = QtWidgets.QToolButton(self.frame_13)
        self.toolButton_positive.setMinimumSize(QtCore.QSize(22, 22))
        self.toolButton_positive.setObjectName("toolButton_positive")
        self.gridLayout_29.addWidget(self.toolButton_positive, 5, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_29.addItem(spacerItem1, 0, 1, 1, 2)
        self.gridLayout_26.addWidget(self.frame_13, 1, 0, 1, 1)
        self.d.addTab(self.sdfsd, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_10 = QtWidgets.QFrame(self.tab)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.connect_microscope = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_microscope.sizePolicy().hasHeightForWidth())
        self.connect_microscope.setSizePolicy(sizePolicy)
        self.connect_microscope.setObjectName("connect_microscope")
        self.verticalLayout_2.addWidget(self.connect_microscope)
        self.to_light_microscope = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_light_microscope.sizePolicy().hasHeightForWidth())
        self.to_light_microscope.setSizePolicy(sizePolicy)
        self.to_light_microscope.setObjectName("to_light_microscope")
        self.verticalLayout_2.addWidget(self.to_light_microscope)
        self.to_electron_microscope = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_electron_microscope.sizePolicy().hasHeightForWidth())
        self.to_electron_microscope.setSizePolicy(sizePolicy)
        self.to_electron_microscope.setObjectName("to_electron_microscope")
        self.verticalLayout_2.addWidget(self.to_electron_microscope)
        self.gridLayout_5.addWidget(self.frame_10, 0, 0, 1, 1)
        self.d.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.d)
        self.horizontalLayout.addWidget(self.frame_volume)
        self.line = QtWidgets.QFrame(self.Main_Frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.frame_fluorescence = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_fluorescence.sizePolicy().hasHeightForWidth())
        self.frame_fluorescence.setSizePolicy(sizePolicy)
        self.frame_fluorescence.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_fluorescence.setMaximumSize(QtCore.QSize(980, 914))
        self.frame_fluorescence.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fluorescence.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fluorescence.setObjectName("frame_fluorescence")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_fluorescence)
        self.gridLayout_4.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_save_destination_FM = QtWidgets.QFrame(self.frame_fluorescence)
        self.frame_save_destination_FM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_save_destination_FM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_save_destination_FM.setObjectName("frame_save_destination_FM")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_save_destination_FM)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_save_destination_FM = QtWidgets.QLabel(self.frame_save_destination_FM)
        self.label_save_destination_FM.setObjectName("label_save_destination_FM")
        self.gridLayout_3.addWidget(self.label_save_destination_FM, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 2, 0, 1, 1)
        self.checkBox_save_destination_FM = QtWidgets.QCheckBox(self.frame_save_destination_FM)
        self.checkBox_save_destination_FM.setMinimumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination_FM.setMaximumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination_FM.setObjectName("checkBox_save_destination_FM")
        self.gridLayout_3.addWidget(self.checkBox_save_destination_FM, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 4, 1, 1)
        self.label_save_filename_FM = QtWidgets.QLabel(self.frame_save_destination_FM)
        self.label_save_filename_FM.setObjectName("label_save_filename_FM")
        self.gridLayout_3.addWidget(self.label_save_filename_FM, 3, 1, 1, 1)
        self.lineEdit_save_destination_FM = QtWidgets.QLineEdit(self.frame_save_destination_FM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_save_destination_FM.sizePolicy().hasHeightForWidth())
        self.lineEdit_save_destination_FM.setSizePolicy(sizePolicy)
        self.lineEdit_save_destination_FM.setMinimumSize(QtCore.QSize(480, 20))
        self.lineEdit_save_destination_FM.setMaximumSize(QtCore.QSize(12356345, 345345))
        self.lineEdit_save_destination_FM.setObjectName("lineEdit_save_destination_FM")
        self.gridLayout_3.addWidget(self.lineEdit_save_destination_FM, 2, 1, 1, 2)
        self.button_save_destination_FM = QtWidgets.QToolButton(self.frame_save_destination_FM)
        self.button_save_destination_FM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_save_destination_FM.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.button_save_destination_FM.setObjectName("button_save_destination_FM")
        self.gridLayout_3.addWidget(self.button_save_destination_FM, 2, 3, 1, 1)
        self.label_FM = QtWidgets.QLabel(self.frame_save_destination_FM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FM.sizePolicy().hasHeightForWidth())
        self.label_FM.setSizePolicy(sizePolicy)
        self.label_FM.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FM.setObjectName("label_FM")
        self.gridLayout_3.addWidget(self.label_FM, 0, 1, 1, 3)
        self.lineEdit_save_filename_FM = QtWidgets.QLineEdit(self.frame_save_destination_FM)
        self.lineEdit_save_filename_FM.setObjectName("lineEdit_save_filename_FM")
        self.gridLayout_3.addWidget(self.lineEdit_save_filename_FM, 4, 1, 1, 2)
        self.label_max_FM_value = QtWidgets.QLabel(self.frame_save_destination_FM)
        self.label_max_FM_value.setObjectName("label_max_FM_value")
        self.gridLayout_3.addWidget(self.label_max_FM_value, 4, 3, 1, 2)
        self.gridLayout_4.addWidget(self.frame_save_destination_FM, 0, 0, 1, 1)
        self.frame_label_fluorescence = QtWidgets.QFrame(self.frame_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_fluorescence.sizePolicy().hasHeightForWidth())
        self.frame_label_fluorescence.setSizePolicy(sizePolicy)
        self.frame_label_fluorescence.setMinimumSize(QtCore.QSize(640, 400))
        self.frame_label_fluorescence.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_fluorescence.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_fluorescence.setObjectName("frame_label_fluorescence")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_label_fluorescence)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_image_FM = QtWidgets.QLabel(self.frame_label_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_FM.sizePolicy().hasHeightForWidth())
        self.label_image_FM.setSizePolicy(sizePolicy)
        self.label_image_FM.setMinimumSize(QtCore.QSize(0, 0))
        self.label_image_FM.setMaximumSize(QtCore.QSize(650, 410))
        self.label_image_FM.setText("")
        self.label_image_FM.setObjectName("label_image_FM")
        self.gridLayout_17.addWidget(self.label_image_FM, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_4.addWidget(self.frame_label_fluorescence, 1, 0, 1, 1)
        self.frame_buttons_FM = QtWidgets.QFrame(self.frame_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons_FM.sizePolicy().hasHeightForWidth())
        self.frame_buttons_FM.setSizePolicy(sizePolicy)
        self.frame_buttons_FM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_FM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_FM.setObjectName("frame_buttons_FM")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_buttons_FM)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setSpacing(4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_4 = QtWidgets.QFrame(self.frame_buttons_FM)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_get_image_FM = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_FM.sizePolicy().hasHeightForWidth())
        self.button_get_image_FM.setSizePolicy(sizePolicy)
        self.button_get_image_FM.setMinimumSize(QtCore.QSize(100, 0))
        self.button_get_image_FM.setObjectName("button_get_image_FM")
        self.horizontalLayout_3.addWidget(self.button_get_image_FM)
        self.button_live_image_FM = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_live_image_FM.sizePolicy().hasHeightForWidth())
        self.button_live_image_FM.setSizePolicy(sizePolicy)
        self.button_live_image_FM.setMinimumSize(QtCore.QSize(100, 0))
        self.button_live_image_FM.setObjectName("button_live_image_FM")
        self.horizontalLayout_3.addWidget(self.button_live_image_FM)
        self.frame_5 = QtWidgets.QFrame(self.frame_9)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_22.setContentsMargins(9, 1, 9, 1)
        self.gridLayout_22.setSpacing(3)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.radioButton_Widefield = QtWidgets.QRadioButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_Widefield.sizePolicy().hasHeightForWidth())
        self.radioButton_Widefield.setSizePolicy(sizePolicy)
        self.radioButton_Widefield.setChecked(True)
        self.radioButton_Widefield.setObjectName("radioButton_Widefield")
        self.gridLayout_22.addWidget(self.radioButton_Widefield, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.radioButton_SIM = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_SIM.setObjectName("radioButton_SIM")
        self.gridLayout_22.addWidget(self.radioButton_SIM, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_pattern_next = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pattern_next.sizePolicy().hasHeightForWidth())
        self.pushButton_pattern_next.setSizePolicy(sizePolicy)
        self.pushButton_pattern_next.setMinimumSize(QtCore.QSize(0, 45))
        self.pushButton_pattern_next.setObjectName("pushButton_pattern_next")
        self.gridLayout_22.addWidget(self.pushButton_pattern_next, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_22.addWidget(self.label, 3, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.gridLayout_18.addWidget(self.frame_4, 4, 1, 2, 1)
        self.gridLayout_4.addWidget(self.frame_buttons_FM, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_fluorescence)
        self.line_2 = QtWidgets.QFrame(self.Main_Frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.frame_FIBSEM = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_FIBSEM.setAutoFillBackground(False)
        self.frame_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_FIBSEM.setObjectName("frame_FIBSEM")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_FIBSEM)
        self.gridLayout.setContentsMargins(9, 0, 9, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_label_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_label_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_label_FIBSEM.setMinimumSize(QtCore.QSize(640, 400))
        self.frame_label_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_FIBSEM.setObjectName("frame_label_FIBSEM")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_label_FIBSEM)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_image_FIBSEM = QtWidgets.QLabel(self.frame_label_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_FIBSEM.sizePolicy().hasHeightForWidth())
        self.label_image_FIBSEM.setSizePolicy(sizePolicy)
        self.label_image_FIBSEM.setMaximumSize(QtCore.QSize(640, 400))
        self.label_image_FIBSEM.setText("")
        self.label_image_FIBSEM.setObjectName("label_image_FIBSEM")
        self.gridLayout_14.addWidget(self.label_image_FIBSEM, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.frame_label_FIBSEM, 2, 0, 1, 2)
        self.frame_save_destination_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_save_destination_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_save_destination_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_save_destination_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_save_destination_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_save_destination_FIBSEM.setObjectName("frame_save_destination_FIBSEM")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_save_destination_FIBSEM)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 2, 5, 1, 1)
        self.lineEdit_save_destination_FIBSEM = QtWidgets.QLineEdit(self.frame_save_destination_FIBSEM)
        self.lineEdit_save_destination_FIBSEM.setMinimumSize(QtCore.QSize(480, 20))
        self.lineEdit_save_destination_FIBSEM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_save_destination_FIBSEM.setObjectName("lineEdit_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.lineEdit_save_destination_FIBSEM, 2, 1, 1, 3)
        self.checkBox_save_destination_FIBSEM = QtWidgets.QCheckBox(self.frame_save_destination_FIBSEM)
        self.checkBox_save_destination_FIBSEM.setMinimumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination_FIBSEM.setMaximumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination_FIBSEM.setObjectName("checkBox_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.checkBox_save_destination_FIBSEM, 1, 3, 1, 1)
        self.button_save_destination_FIBSEM = QtWidgets.QToolButton(self.frame_save_destination_FIBSEM)
        self.button_save_destination_FIBSEM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_save_destination_FIBSEM.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.button_save_destination_FIBSEM.setObjectName("button_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.button_save_destination_FIBSEM, 2, 4, 1, 1)
        self.label_save_filename_FIBSEM = QtWidgets.QLabel(self.frame_save_destination_FIBSEM)
        self.label_save_filename_FIBSEM.setObjectName("label_save_filename_FIBSEM")
        self.gridLayout_7.addWidget(self.label_save_filename_FIBSEM, 3, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem5, 2, 0, 1, 1)
        self.label_save_destination_FIBSEM = QtWidgets.QLabel(self.frame_save_destination_FIBSEM)
        self.label_save_destination_FIBSEM.setObjectName("label_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.label_save_destination_FIBSEM, 1, 1, 1, 1)
        self.lineEdit_save_filename_FIBSEM = QtWidgets.QLineEdit(self.frame_save_destination_FIBSEM)
        self.lineEdit_save_filename_FIBSEM.setObjectName("lineEdit_save_filename_FIBSEM")
        self.gridLayout_7.addWidget(self.lineEdit_save_filename_FIBSEM, 4, 1, 1, 4)
        self.label_FIBSEM = QtWidgets.QLabel(self.frame_save_destination_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FIBSEM.sizePolicy().hasHeightForWidth())
        self.label_FIBSEM.setSizePolicy(sizePolicy)
        self.label_FIBSEM.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_FIBSEM.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FIBSEM.setObjectName("label_FIBSEM")
        self.gridLayout_7.addWidget(self.label_FIBSEM, 0, 1, 1, 4)
        self.gridLayout.addWidget(self.frame_save_destination_FIBSEM, 1, 0, 1, 2)
        self.frame_buttons_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_buttons_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_buttons_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_FIBSEM.setObjectName("frame_buttons_FIBSEM")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_buttons_FIBSEM)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_2 = QtWidgets.QFrame(self.frame_buttons_FIBSEM)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.button_get_image_FIB = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_FIB.sizePolicy().hasHeightForWidth())
        self.button_get_image_FIB.setSizePolicy(sizePolicy)
        self.button_get_image_FIB.setObjectName("button_get_image_FIB")
        self.gridLayout_13.addWidget(self.button_get_image_FIB, 0, 0, 1, 1)
        self.button_get_image_SEM = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_SEM.sizePolicy().hasHeightForWidth())
        self.button_get_image_SEM.setSizePolicy(sizePolicy)
        self.button_get_image_SEM.setObjectName("button_get_image_SEM")
        self.gridLayout_13.addWidget(self.button_get_image_SEM, 0, 1, 1, 1)
        self.button_last_image_FIB = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_last_image_FIB.sizePolicy().hasHeightForWidth())
        self.button_last_image_FIB.setSizePolicy(sizePolicy)
        self.button_last_image_FIB.setObjectName("button_last_image_FIB")
        self.gridLayout_13.addWidget(self.button_last_image_FIB, 1, 0, 1, 1)
        self.button_last_image_SEM = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_last_image_SEM.sizePolicy().hasHeightForWidth())
        self.button_last_image_SEM.setSizePolicy(sizePolicy)
        self.button_last_image_SEM.setObjectName("button_last_image_SEM")
        self.gridLayout_13.addWidget(self.button_last_image_SEM, 1, 1, 1, 1)
        self.gridLayout_20.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_buttons_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_16.setContentsMargins(-1, 1, -1, 1)
        self.gridLayout_16.setVerticalSpacing(3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.pushButton_milling = QtWidgets.QPushButton(self.frame)
        self.pushButton_milling.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_milling.setObjectName("pushButton_milling")
        self.gridLayout_16.addWidget(self.pushButton_milling, 5, 0, 1, 2)
        self.pushButton_correlation = QtWidgets.QPushButton(self.frame)
        self.pushButton_correlation.setMinimumSize(QtCore.QSize(0, 33))
        self.pushButton_correlation.setObjectName("pushButton_correlation")
        self.gridLayout_16.addWidget(self.pushButton_correlation, 2, 0, 1, 2)
        self.correlation_output_path = QtWidgets.QLineEdit(self.frame)
        self.correlation_output_path.setObjectName("correlation_output_path")
        self.gridLayout_16.addWidget(self.correlation_output_path, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_16.addWidget(self.label_2, 0, 0, 1, 2)
        self.toolButton_correlation_output = QtWidgets.QToolButton(self.frame)
        self.toolButton_correlation_output.setObjectName("toolButton_correlation_output")
        self.gridLayout_16.addWidget(self.toolButton_correlation_output, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_16.addItem(spacerItem6, 3, 0, 1, 1)
        self.gridLayout_20.addWidget(self.frame, 0, 3, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_buttons_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(245, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lineEdit_dwell_time = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dwell_time.sizePolicy().hasHeightForWidth())
        self.lineEdit_dwell_time.setSizePolicy(sizePolicy)
        self.lineEdit_dwell_time.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_dwell_time.setObjectName("lineEdit_dwell_time")
        self.verticalLayout_3.addWidget(self.lineEdit_dwell_time)
        self.checkBox_Autocontrast = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_Autocontrast.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_Autocontrast.setObjectName("checkBox_Autocontrast")
        self.verticalLayout_3.addWidget(self.checkBox_Autocontrast)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.comboBox_resolution = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_resolution.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_resolution.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_resolution.setObjectName("comboBox_resolution")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_resolution)
        self.gridLayout_20.addWidget(self.frame_3, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.frame_buttons_FIBSEM, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_FIBSEM)
        MainGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1623, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menuFile)
        self.menuHelp.setObjectName("menuHelp")
        MainGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainGui)
        self.statusbar.setObjectName("statusbar")
        MainGui.setStatusBar(self.statusbar)
        self.actionOpen_FM_Image = QtWidgets.QAction(MainGui)
        self.actionOpen_FM_Image.setObjectName("actionOpen_FM_Image")
        self.actionOpen_FIBSEM_Image = QtWidgets.QAction(MainGui)
        self.actionOpen_FIBSEM_Image.setObjectName("actionOpen_FIBSEM_Image")
        self.actionSave_FM_Image = QtWidgets.QAction(MainGui)
        self.actionSave_FM_Image.setObjectName("actionSave_FM_Image")
        self.actionSave_FIBSEM_Image = QtWidgets.QAction(MainGui)
        self.actionSave_FIBSEM_Image.setObjectName("actionSave_FIBSEM_Image")
        self.actionAbout = QtWidgets.QAction(MainGui)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOpen.addAction(self.actionOpen_FM_Image)
        self.menuOpen.addAction(self.actionOpen_FIBSEM_Image)
        self.menuSave.addAction(self.actionSave_FM_Image)
        self.menuSave.addAction(self.actionSave_FIBSEM_Image)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainGui)
        self.d.setCurrentIndex(0)
        self.spinBox_laser1.valueChanged['int'].connect(self.slider_laser1.setValue)
        self.slider_laser1.valueChanged['int'].connect(self.spinBox_laser1.setValue)
        self.spinBox_laser2.valueChanged['int'].connect(self.slider_laser2.setValue)
        self.slider_laser2.valueChanged['int'].connect(self.spinBox_laser2.setValue)
        self.spinBox_laser3.valueChanged['int'].connect(self.slider_laser3.setValue)
        self.slider_laser3.valueChanged['int'].connect(self.spinBox_laser3.setValue)
        self.spinBox_laser4.valueChanged['int'].connect(self.slider_laser4.setValue)
        self.slider_laser4.valueChanged['int'].connect(self.spinBox_laser4.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainGui)
        MainGui.setTabOrder(self.pushButton_correlation, self.pushButton_milling)
        MainGui.setTabOrder(self.pushButton_milling, self.lineEdit_save_destination_FM)
        MainGui.setTabOrder(self.lineEdit_save_destination_FM, self.checkBox_save_destination_FM)
        MainGui.setTabOrder(self.checkBox_save_destination_FM, self.button_save_destination_FM)
        MainGui.setTabOrder(self.button_save_destination_FM, self.lineEdit_save_filename_FM)
        MainGui.setTabOrder(self.lineEdit_save_filename_FM, self.lineEdit_save_destination_FIBSEM)
        MainGui.setTabOrder(self.lineEdit_save_destination_FIBSEM, self.checkBox_save_destination_FIBSEM)
        MainGui.setTabOrder(self.checkBox_save_destination_FIBSEM, self.button_save_destination_FIBSEM)
        MainGui.setTabOrder(self.button_save_destination_FIBSEM, self.lineEdit_save_filename_FIBSEM)
        MainGui.setTabOrder(self.lineEdit_save_filename_FIBSEM, self.button_get_image_FIB)
        MainGui.setTabOrder(self.button_get_image_FIB, self.button_get_image_SEM)
        MainGui.setTabOrder(self.button_get_image_SEM, self.button_last_image_FIB)
        MainGui.setTabOrder(self.button_last_image_FIB, self.button_last_image_SEM)
        MainGui.setTabOrder(self.button_last_image_SEM, self.lineEdit_dwell_time)
        MainGui.setTabOrder(self.lineEdit_dwell_time, self.comboBox_resolution)

    def retranslateUi(self, MainGui):
        _translate = QtCore.QCoreApplication.translate
        MainGui.setWindowTitle(_translate("MainGui", "MainWindow"))
        self.label_exposure_8.setText(_translate("MainGui", "Exposure (ms)"))
        self.lineEdit_exposure_1.setText(_translate("MainGui", "1000"))
        self.checkBox_laser1.setText(_translate("MainGui", "640nm"))
        self.lineEdit_exposure_2.setText(_translate("MainGui", "1000"))
        self.label_exposure_6.setText(_translate("MainGui", "Exposure (ms)"))
        self.checkBox_laser2.setText(_translate("MainGui", "561nm"))
        self.lineEdit_exposure_3.setText(_translate("MainGui", "1000"))
        self.checkBox_laser3.setText(_translate("MainGui", "488nm"))
        self.label_exposure_7.setText(_translate("MainGui", "Exposure (ms)"))
        self.label_exposure_9.setText(_translate("MainGui", "Exposure (ms)"))
        self.lineEdit_exposure_4.setText(_translate("MainGui", "1000"))
        self.checkBox_laser4.setText(_translate("MainGui", "405nm"))
        self.label_volume_title.setText(_translate("MainGui", "Volume Acquisition"))
        self.comboBox_2.setItemText(0, _translate("MainGui", "Total Volume Height (nm)"))
        self.comboBox_2.setItemText(1, _translate("MainGui", "+/- Volume Height (nm)"))
        self.pushButton_volume.setText(_translate("MainGui", "Acquire Volume"))
        self.comboBox.setItemText(0, _translate("MainGui", "Slice Distance (nm)"))
        self.comboBox.setItemText(1, _translate("MainGui", "Slice Number "))
        self.pushButton_save_objective_position.setText(_translate("MainGui", "Save Position"))
        self.label_7.setText(_translate("MainGui", "Absolute Position (um)"))
        self.pushButton_go_to_saved_position.setText(_translate("MainGui", "Go to saved position"))
        self.pushButton_initialize_stage.setText(_translate("MainGui", "Initialise Stage"))
        self.pushButton_get_position.setText(_translate("MainGui", "Get Position"))
        self.label_8.setText(_translate("MainGui", "Saved Position (um)"))
        self.toolButton_negative.setText(_translate("MainGui", "-"))
        self.pushButton_move_absolute.setText(_translate("MainGui", "Move Absolute (um)"))
        self.pushButton_move_relative.setText(_translate("MainGui", "Move Relative (um)"))
        self.toolButton_positive.setText(_translate("MainGui", "+"))
        self.d.setTabText(self.d.indexOf(self.sdfsd), _translate("MainGui", "Objective movement"))
        self.connect_microscope.setText(_translate("MainGui", "Connect to microscope"))
        self.to_light_microscope.setText(_translate("MainGui", "To Light Microscope"))
        self.to_electron_microscope.setText(_translate("MainGui", "To Electron Microscope"))
        self.d.setTabText(self.d.indexOf(self.tab), _translate("MainGui", "Stage movement"))
        self.label_save_destination_FM.setText(_translate("MainGui", "Save Destination"))
        self.checkBox_save_destination_FM.setText(_translate("MainGui", "Lock Save Destination"))
        self.label_save_filename_FM.setText(_translate("MainGui", "Save Filename"))
        self.button_save_destination_FM.setText(_translate("MainGui", "..."))
        self.label_FM.setText(_translate("MainGui", "FM"))
        self.label_max_FM_value.setText(_translate("MainGui", "Max Value: "))
        self.button_get_image_FM.setText(_translate("MainGui", "Get Basler Image"))
        self.button_live_image_FM.setText(_translate("MainGui", "Live Basler View"))
        self.radioButton_Widefield.setText(_translate("MainGui", "Widefield"))
        self.radioButton_SIM.setText(_translate("MainGui", "SIM"))
        self.pushButton_pattern_next.setText(_translate("MainGui", "Next Pattern"))
        self.label.setText(_translate("MainGui", "Pattern: "))
        self.checkBox_save_destination_FIBSEM.setText(_translate("MainGui", "Lock Save Destination"))
        self.button_save_destination_FIBSEM.setText(_translate("MainGui", "..."))
        self.label_save_filename_FIBSEM.setText(_translate("MainGui", "Save Filename"))
        self.label_save_destination_FIBSEM.setText(_translate("MainGui", "Save Destination"))
        self.label_FIBSEM.setText(_translate("MainGui", "FIBSEM"))
        self.button_get_image_FIB.setText(_translate("MainGui", "Get FIB Image"))
        self.button_get_image_SEM.setText(_translate("MainGui", "Get SEM Image"))
        self.button_last_image_FIB.setText(_translate("MainGui", "Grab Last FIB"))
        self.button_last_image_SEM.setText(_translate("MainGui", "Grab Last SEM"))
        self.pushButton_milling.setText(_translate("MainGui", "Milling"))
        self.pushButton_correlation.setText(_translate("MainGui", "Correlation"))
        self.label_2.setText(_translate("MainGui", "Correlation Save Destination"))
        self.toolButton_correlation_output.setText(_translate("MainGui", "..."))
        self.label_3.setText(_translate("MainGui", "Dwell Time (us)"))
        self.lineEdit_dwell_time.setText(_translate("MainGui", "1"))
        self.checkBox_Autocontrast.setText(_translate("MainGui", "Autocontrast"))
        self.label_4.setText(_translate("MainGui", "Resolution"))
        self.comboBox_resolution.setItemText(0, _translate("MainGui", "768x512"))
        self.comboBox_resolution.setItemText(1, _translate("MainGui", "1536x1024"))
        self.comboBox_resolution.setItemText(2, _translate("MainGui", "3072x2048"))
        self.comboBox_resolution.setItemText(3, _translate("MainGui", "6144x4096"))
        self.menuFile.setTitle(_translate("MainGui", "File"))
        self.menuOpen.setTitle(_translate("MainGui", "Open"))
        self.menuSave.setTitle(_translate("MainGui", "Save"))
        self.menuHelp.setTitle(_translate("MainGui", "Help"))
        self.actionOpen_FM_Image.setText(_translate("MainGui", "Open FM Image"))
        self.actionOpen_FIBSEM_Image.setText(_translate("MainGui", "Open FIBSEM Image"))
        self.actionSave_FM_Image.setText(_translate("MainGui", "Save FM Image"))
        self.actionSave_FIBSEM_Image.setText(_translate("MainGui", "Save FIBSEM Image"))
        self.actionAbout.setText(_translate("MainGui", "About"))

