# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainGui(object):
    def setupUi(self, MainGui):
        MainGui.setObjectName("MainGui")
        MainGui.resize(1850, 739)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainGui.sizePolicy().hasHeightForWidth())
        MainGui.setSizePolicy(sizePolicy)
        MainGui.setMinimumSize(QtCore.QSize(1623, 739))
        MainGui.setMaximumSize(QtCore.QSize(1850, 750))
        self.centralwidget = QtWidgets.QWidget(MainGui)
        self.centralwidget.setMaximumSize(QtCore.QSize(1850, 750))
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Frame.setGeometry(QtCore.QRect(0, 0, 1850, 698))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Main_Frame.sizePolicy().hasHeightForWidth())
        self.Main_Frame.setSizePolicy(sizePolicy)
        self.Main_Frame.setMinimumSize(QtCore.QSize(1850, 698))
        self.Main_Frame.setMaximumSize(QtCore.QSize(1850, 750))
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Frame.setObjectName("Main_Frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Main_Frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_volume = QtWidgets.QFrame(self.Main_Frame)
        self.frame_volume.setMinimumSize(QtCore.QSize(271, 696))
        self.frame_volume.setMaximumSize(QtCore.QSize(271, 696))
        self.frame_volume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_volume.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_volume.setObjectName("frame_volume")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_volume)
        self.gridLayout_6.setContentsMargins(3, 1, 1, 1)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_10 = QtWidgets.QFrame(self.frame_volume)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setVerticalSpacing(8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_move_relative = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_move_relative.setEnabled(False)
        self.pushButton_move_relative.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_move_relative.setObjectName("pushButton_move_relative")
        self.gridLayout_5.addWidget(self.pushButton_move_relative, 11, 0, 1, 4)
        self.label_objective_stage_saved_position = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_objective_stage_saved_position.sizePolicy().hasHeightForWidth())
        self.label_objective_stage_saved_position.setSizePolicy(sizePolicy)
        self.label_objective_stage_saved_position.setMinimumSize(QtCore.QSize(0, 20))
        self.label_objective_stage_saved_position.setText("")
        self.label_objective_stage_saved_position.setObjectName("label_objective_stage_saved_position")
        self.gridLayout_5.addWidget(self.label_objective_stage_saved_position, 3, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.frame_10)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 13, 0, 1, 3)
        self.pushButton_go_to_saved_position = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_go_to_saved_position.setEnabled(False)
        self.pushButton_go_to_saved_position.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_go_to_saved_position.setObjectName("pushButton_go_to_saved_position")
        self.gridLayout_5.addWidget(self.pushButton_go_to_saved_position, 7, 0, 1, 4)
        self.lineEdit_move_absolute = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_move_absolute.setEnabled(False)
        self.lineEdit_move_absolute.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_move_absolute.setObjectName("lineEdit_move_absolute")
        self.gridLayout_5.addWidget(self.lineEdit_move_absolute, 9, 0, 1, 4)
        self.label_23 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 1, 0, 1, 4)
        self.pushButton_move_absolute = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_move_absolute.setEnabled(False)
        self.pushButton_move_absolute.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_move_absolute.setObjectName("pushButton_move_absolute")
        self.gridLayout_5.addWidget(self.pushButton_move_absolute, 8, 0, 1, 4)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 35))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButton_negative = QtWidgets.QToolButton(self.frame_11)
        self.toolButton_negative.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_negative.sizePolicy().hasHeightForWidth())
        self.toolButton_negative.setSizePolicy(sizePolicy)
        self.toolButton_negative.setMinimumSize(QtCore.QSize(22, 22))
        self.toolButton_negative.setObjectName("toolButton_negative")
        self.horizontalLayout_4.addWidget(self.toolButton_negative)
        self.lineEdit_move_relative = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_move_relative.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_move_relative.sizePolicy().hasHeightForWidth())
        self.lineEdit_move_relative.setSizePolicy(sizePolicy)
        self.lineEdit_move_relative.setMinimumSize(QtCore.QSize(0, 24))
        self.lineEdit_move_relative.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lineEdit_move_relative.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_move_relative.setObjectName("lineEdit_move_relative")
        self.horizontalLayout_4.addWidget(self.lineEdit_move_relative)
        self.toolButton_positive = QtWidgets.QToolButton(self.frame_11)
        self.toolButton_positive.setEnabled(False)
        self.toolButton_positive.setMinimumSize(QtCore.QSize(22, 22))
        self.toolButton_positive.setObjectName("toolButton_positive")
        self.horizontalLayout_4.addWidget(self.toolButton_positive)
        self.gridLayout_5.addWidget(self.frame_11, 12, 0, 1, 4)
        self.label_objective_stage_position = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_objective_stage_position.sizePolicy().hasHeightForWidth())
        self.label_objective_stage_position.setSizePolicy(sizePolicy)
        self.label_objective_stage_position.setText("")
        self.label_objective_stage_position.setObjectName("label_objective_stage_position")
        self.gridLayout_5.addWidget(self.label_objective_stage_position, 2, 1, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 1, 4)
        self.pushButton_get_position = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_get_position.setEnabled(False)
        self.pushButton_get_position.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_get_position.setObjectName("pushButton_get_position")
        self.gridLayout_5.addWidget(self.pushButton_get_position, 4, 0, 1, 1)
        self.pushButton_save_objective_position = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_save_objective_position.setEnabled(False)
        self.pushButton_save_objective_position.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_save_objective_position.setObjectName("pushButton_save_objective_position")
        self.gridLayout_5.addWidget(self.pushButton_save_objective_position, 4, 1, 1, 3)
        self.gridLayout_6.addWidget(self.frame_10, 6, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_volume)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_laser4 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_laser4.setEnabled(False)
        self.checkBox_laser4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser4.setObjectName("checkBox_laser4")
        self.gridLayout_2.addWidget(self.checkBox_laser4, 3, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 1, 5)
        self.pushButton_volume = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_volume.setEnabled(False)
        self.pushButton_volume.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_volume.setFlat(False)
        self.pushButton_volume.setObjectName("pushButton_volume")
        self.gridLayout_2.addWidget(self.pushButton_volume, 6, 0, 1, 5)
        self.label_exposure_9 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_exposure_9.setFont(font)
        self.label_exposure_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_exposure_9.setObjectName("label_exposure_9")
        self.gridLayout_2.addWidget(self.label_exposure_9, 4, 0, 1, 2)
        self.checkBox_laser2 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_laser2.setEnabled(False)
        self.checkBox_laser2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser2.setObjectName("checkBox_laser2")
        self.gridLayout_2.addWidget(self.checkBox_laser2, 3, 1, 1, 1)
        self.label_exposure_10 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_exposure_10.setFont(font)
        self.label_exposure_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_exposure_10.setObjectName("label_exposure_10")
        self.gridLayout_2.addWidget(self.label_exposure_10, 4, 3, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 5)
        self.lineEdit_slice_distance = QtWidgets.QLineEdit(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_slice_distance.sizePolicy().hasHeightForWidth())
        self.lineEdit_slice_distance.setSizePolicy(sizePolicy)
        self.lineEdit_slice_distance.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_slice_distance.setObjectName("lineEdit_slice_distance")
        self.gridLayout_2.addWidget(self.lineEdit_slice_distance, 5, 0, 1, 2)
        self.checkBox_laser1 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_laser1.setEnabled(False)
        self.checkBox_laser1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser1.setObjectName("checkBox_laser1")
        self.gridLayout_2.addWidget(self.checkBox_laser1, 3, 0, 1, 1)
        self.lineEdit_volume_height = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_volume_height.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_volume_height.setObjectName("lineEdit_volume_height")
        self.gridLayout_2.addWidget(self.lineEdit_volume_height, 5, 3, 1, 2)
        self.checkBox_laser3 = QtWidgets.QCheckBox(self.frame_6)
        self.checkBox_laser3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_laser3.sizePolicy().hasHeightForWidth())
        self.checkBox_laser3.setSizePolicy(sizePolicy)
        self.checkBox_laser3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_laser3.setObjectName("checkBox_laser3")
        self.gridLayout_2.addWidget(self.checkBox_laser3, 3, 3, 1, 1)
        self.gridLayout_6.addWidget(self.frame_6, 5, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_volume)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setContentsMargins(1, -1, 1, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_8.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_exposure_8 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_exposure_8.setFont(font)
        self.label_exposure_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_exposure_8.setObjectName("label_exposure_8")
        self.gridLayout_8.addWidget(self.label_exposure_8, 2, 2, 1, 1)
        self.lineEdit_exposure_3 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_exposure_3.setEnabled(False)
        self.lineEdit_exposure_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_exposure_3.setObjectName("lineEdit_exposure_3")
        self.gridLayout_8.addWidget(self.lineEdit_exposure_3, 5, 2, 1, 1)
        self.doubleSpinBox_laser1 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_laser1.setEnabled(False)
        self.doubleSpinBox_laser1.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_laser1.setObjectName("doubleSpinBox_laser1")
        self.gridLayout_8.addWidget(self.doubleSpinBox_laser1, 3, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 0, 0, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 3, 0, 1, 1)
        self.lineEdit_exposure_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_exposure_2.setEnabled(False)
        self.lineEdit_exposure_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_exposure_2.setObjectName("lineEdit_exposure_2")
        self.gridLayout_8.addWidget(self.lineEdit_exposure_2, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_7)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_7)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 5, 0, 1, 1)
        self.lineEdit_exposure_1 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_exposure_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_exposure_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_exposure_1.setSizePolicy(sizePolicy)
        self.lineEdit_exposure_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_exposure_1.setObjectName("lineEdit_exposure_1")
        self.gridLayout_8.addWidget(self.lineEdit_exposure_1, 3, 2, 1, 1)
        self.doubleSpinBox_laser2 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_laser2.setEnabled(False)
        self.doubleSpinBox_laser2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_laser2.setObjectName("doubleSpinBox_laser2")
        self.gridLayout_8.addWidget(self.doubleSpinBox_laser2, 4, 1, 1, 1)
        self.doubleSpinBox_laser3 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_laser3.setEnabled(False)
        self.doubleSpinBox_laser3.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_laser3.setObjectName("doubleSpinBox_laser3")
        self.gridLayout_8.addWidget(self.doubleSpinBox_laser3, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_7)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 6, 0, 1, 1)
        self.doubleSpinBox_laser4 = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.doubleSpinBox_laser4.setEnabled(False)
        self.doubleSpinBox_laser4.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_laser4.setObjectName("doubleSpinBox_laser4")
        self.gridLayout_8.addWidget(self.doubleSpinBox_laser4, 6, 1, 1, 1)
        self.lineEdit_exposure_4 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_exposure_4.setEnabled(False)
        self.lineEdit_exposure_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_exposure_4.setObjectName("lineEdit_exposure_4")
        self.gridLayout_8.addWidget(self.lineEdit_exposure_4, 6, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame_7, 1, 0, 1, 1)
        self.pushButton_stage_movement = QtWidgets.QPushButton(self.frame_volume)
        self.pushButton_stage_movement.setEnabled(False)
        self.pushButton_stage_movement.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_stage_movement.setObjectName("pushButton_stage_movement")
        self.gridLayout_6.addWidget(self.pushButton_stage_movement, 8, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_volume)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 7, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_volume)
        self.line = QtWidgets.QFrame(self.Main_Frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.frame_fluorescence = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_fluorescence.sizePolicy().hasHeightForWidth())
        self.frame_fluorescence.setSizePolicy(sizePolicy)
        self.frame_fluorescence.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_fluorescence.setMaximumSize(QtCore.QSize(980, 914))
        self.frame_fluorescence.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fluorescence.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fluorescence.setObjectName("frame_fluorescence")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_fluorescence)
        self.gridLayout_4.setContentsMargins(9, 0, 9, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_label_fluorescence = QtWidgets.QFrame(self.frame_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_fluorescence.sizePolicy().hasHeightForWidth())
        self.frame_label_fluorescence.setSizePolicy(sizePolicy)
        self.frame_label_fluorescence.setMinimumSize(QtCore.QSize(640, 400))
        self.frame_label_fluorescence.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_fluorescence.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_fluorescence.setObjectName("frame_label_fluorescence")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_label_fluorescence)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_image_FM = QtWidgets.QLabel(self.frame_label_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_FM.sizePolicy().hasHeightForWidth())
        self.label_image_FM.setSizePolicy(sizePolicy)
        self.label_image_FM.setMinimumSize(QtCore.QSize(650, 400))
        self.label_image_FM.setMaximumSize(QtCore.QSize(650, 400))
        self.label_image_FM.setText("")
        self.label_image_FM.setObjectName("label_image_FM")
        self.gridLayout_17.addWidget(self.label_image_FM, 2, 1, 1, 1)
        self.label_FM = QtWidgets.QLabel(self.frame_label_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FM.sizePolicy().hasHeightForWidth())
        self.label_FM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_FM.setFont(font)
        self.label_FM.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FM.setObjectName("label_FM")
        self.gridLayout_17.addWidget(self.label_FM, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame_label_fluorescence, 1, 1, 1, 1)
        self.frame_buttons_FM = QtWidgets.QFrame(self.frame_fluorescence)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons_FM.sizePolicy().hasHeightForWidth())
        self.frame_buttons_FM.setSizePolicy(sizePolicy)
        self.frame_buttons_FM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_FM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_FM.setObjectName("frame_buttons_FM")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_buttons_FM)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setSpacing(4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_4 = QtWidgets.QFrame(self.frame_buttons_FM)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_get_image_FM = QtWidgets.QPushButton(self.frame_9)
        self.button_get_image_FM.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_FM.sizePolicy().hasHeightForWidth())
        self.button_get_image_FM.setSizePolicy(sizePolicy)
        self.button_get_image_FM.setMinimumSize(QtCore.QSize(100, 0))
        self.button_get_image_FM.setObjectName("button_get_image_FM")
        self.horizontalLayout_3.addWidget(self.button_get_image_FM)
        self.button_live_image_FM = QtWidgets.QPushButton(self.frame_9)
        self.button_live_image_FM.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_live_image_FM.sizePolicy().hasHeightForWidth())
        self.button_live_image_FM.setSizePolicy(sizePolicy)
        self.button_live_image_FM.setMinimumSize(QtCore.QSize(100, 0))
        self.button_live_image_FM.setObjectName("button_live_image_FM")
        self.horizontalLayout_3.addWidget(self.button_live_image_FM)
        self.frame_fm_imaging_settings = QtWidgets.QFrame(self.frame_9)
        self.frame_fm_imaging_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fm_imaging_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fm_imaging_settings.setObjectName("frame_fm_imaging_settings")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_fm_imaging_settings)
        self.gridLayout_22.setContentsMargins(9, 1, 9, 1)
        self.gridLayout_22.setSpacing(3)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.comboBox_imaging_type = QtWidgets.QComboBox(self.frame_fm_imaging_settings)
        self.comboBox_imaging_type.setEnabled(False)
        self.comboBox_imaging_type.setObjectName("comboBox_imaging_type")
        self.comboBox_imaging_type.addItem("")
        self.comboBox_imaging_type.addItem("")
        self.gridLayout_22.addWidget(self.comboBox_imaging_type, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_fm_imaging_settings)
        self.label_16.setObjectName("label_16")
        self.gridLayout_22.addWidget(self.label_16, 3, 0, 1, 1)
        self.comboBox_cmap = QtWidgets.QComboBox(self.frame_fm_imaging_settings)
        self.comboBox_cmap.setEnabled(False)
        self.comboBox_cmap.setObjectName("comboBox_cmap")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.gridLayout_22.addWidget(self.comboBox_cmap, 2, 1, 1, 1)
        self.comboBox_wavelength = QtWidgets.QComboBox(self.frame_fm_imaging_settings)
        self.comboBox_wavelength.setEnabled(False)
        self.comboBox_wavelength.setObjectName("comboBox_wavelength")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.comboBox_wavelength.addItem("")
        self.gridLayout_22.addWidget(self.comboBox_wavelength, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_fm_imaging_settings)
        self.label_14.setObjectName("label_14")
        self.gridLayout_22.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_fm_imaging_settings)
        self.label_15.setObjectName("label_15")
        self.gridLayout_22.addWidget(self.label_15, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_fm_imaging_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_22.addWidget(self.label, 5, 0, 1, 1)
        self.comboBox_pattern = QtWidgets.QComboBox(self.frame_fm_imaging_settings)
        self.comboBox_pattern.setEnabled(False)
        self.comboBox_pattern.setObjectName("comboBox_pattern")
        self.comboBox_pattern.addItem("")
        self.comboBox_pattern.addItem("")
        self.comboBox_pattern.addItem("")
        self.gridLayout_22.addWidget(self.comboBox_pattern, 5, 1, 1, 1)
        self.label_max_FM_value = QtWidgets.QLabel(self.frame_fm_imaging_settings)
        self.label_max_FM_value.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_max_FM_value.setObjectName("label_max_FM_value")
        self.gridLayout_22.addWidget(self.label_max_FM_value, 6, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_fm_imaging_settings)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.gridLayout_18.addWidget(self.frame_4, 4, 1, 2, 1)
        self.gridLayout_4.addWidget(self.frame_buttons_FM, 3, 1, 1, 1)
        self.frame_save_destination_FM = QtWidgets.QFrame(self.frame_fluorescence)
        self.frame_save_destination_FM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_save_destination_FM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_save_destination_FM.setObjectName("frame_save_destination_FM")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_save_destination_FM)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_save_destination_FM = QtWidgets.QLineEdit(self.frame_save_destination_FM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_save_destination_FM.sizePolicy().hasHeightForWidth())
        self.lineEdit_save_destination_FM.setSizePolicy(sizePolicy)
        self.lineEdit_save_destination_FM.setMinimumSize(QtCore.QSize(400, 10))
        self.lineEdit_save_destination_FM.setMaximumSize(QtCore.QSize(12356345, 20))
        self.lineEdit_save_destination_FM.setObjectName("lineEdit_save_destination_FM")
        self.gridLayout_3.addWidget(self.lineEdit_save_destination_FM, 2, 1, 1, 2)
        self.label_save_filename_FM = QtWidgets.QLabel(self.frame_save_destination_FM)
        self.label_save_filename_FM.setObjectName("label_save_filename_FM")
        self.gridLayout_3.addWidget(self.label_save_filename_FM, 4, 0, 1, 1)
        self.pushButton_load_FM = QtWidgets.QPushButton(self.frame_save_destination_FM)
        self.pushButton_load_FM.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_load_FM.setObjectName("pushButton_load_FM")
        self.gridLayout_3.addWidget(self.pushButton_load_FM, 2, 4, 1, 2)
        self.button_save_destination_FM = QtWidgets.QToolButton(self.frame_save_destination_FM)
        self.button_save_destination_FM.setMinimumSize(QtCore.QSize(25, 25))
        self.button_save_destination_FM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_save_destination_FM.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.button_save_destination_FM.setObjectName("button_save_destination_FM")
        self.gridLayout_3.addWidget(self.button_save_destination_FM, 2, 3, 1, 1)
        self.label_save_destination_FM = QtWidgets.QLabel(self.frame_save_destination_FM)
        self.label_save_destination_FM.setObjectName("label_save_destination_FM")
        self.gridLayout_3.addWidget(self.label_save_destination_FM, 2, 0, 1, 1)
        self.pushButton_save_FM = QtWidgets.QPushButton(self.frame_save_destination_FM)
        self.pushButton_save_FM.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_save_FM.setObjectName("pushButton_save_FM")
        self.gridLayout_3.addWidget(self.pushButton_save_FM, 4, 4, 1, 2)
        self.lineEdit_save_filename_FM = QtWidgets.QLineEdit(self.frame_save_destination_FM)
        self.lineEdit_save_filename_FM.setObjectName("lineEdit_save_filename_FM")
        self.gridLayout_3.addWidget(self.lineEdit_save_filename_FM, 4, 1, 1, 3)
        self.gridLayout_4.addWidget(self.frame_save_destination_FM, 4, 1, 1, 1)
        self.horizontalLayout.addWidget(self.frame_fluorescence)
        self.line_2 = QtWidgets.QFrame(self.Main_Frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.frame_FIBSEM = QtWidgets.QFrame(self.Main_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_FIBSEM.setAutoFillBackground(False)
        self.frame_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_FIBSEM.setObjectName("frame_FIBSEM")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_FIBSEM)
        self.verticalLayout.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_FM_2 = QtWidgets.QLabel(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_FM_2.sizePolicy().hasHeightForWidth())
        self.label_FM_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_FM_2.setFont(font)
        self.label_FM_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_FM_2.setObjectName("label_FM_2")
        self.verticalLayout.addWidget(self.label_FM_2)
        self.frame_label_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_label_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_label_FIBSEM.setMinimumSize(QtCore.QSize(640, 400))
        self.frame_label_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_FIBSEM.setObjectName("frame_label_FIBSEM")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_label_FIBSEM)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_image_FIBSEM = QtWidgets.QLabel(self.frame_label_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image_FIBSEM.sizePolicy().hasHeightForWidth())
        self.label_image_FIBSEM.setSizePolicy(sizePolicy)
        self.label_image_FIBSEM.setMinimumSize(QtCore.QSize(640, 400))
        self.label_image_FIBSEM.setMaximumSize(QtCore.QSize(640, 400))
        self.label_image_FIBSEM.setText("")
        self.label_image_FIBSEM.setObjectName("label_image_FIBSEM")
        self.gridLayout_14.addWidget(self.label_image_FIBSEM, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_label_FIBSEM)
        self.frame_buttons_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_buttons_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_buttons_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buttons_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buttons_FIBSEM.setObjectName("frame_buttons_FIBSEM")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_buttons_FIBSEM)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_3 = QtWidgets.QFrame(self.frame_buttons_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_dwell_time = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_dwell_time.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dwell_time.sizePolicy().hasHeightForWidth())
        self.lineEdit_dwell_time.setSizePolicy(sizePolicy)
        self.lineEdit_dwell_time.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lineEdit_dwell_time.setObjectName("lineEdit_dwell_time")
        self.gridLayout.addWidget(self.lineEdit_dwell_time, 1, 1, 1, 1)
        self.comboBox_resolution = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_resolution.setEnabled(False)
        self.comboBox_resolution.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_resolution.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_resolution.setObjectName("comboBox_resolution")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.comboBox_resolution.addItem("")
        self.gridLayout.addWidget(self.comboBox_resolution, 4, 1, 1, 1)
        self.checkBox_Autocontrast = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_Autocontrast.setEnabled(False)
        self.checkBox_Autocontrast.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_Autocontrast.setObjectName("checkBox_Autocontrast")
        self.gridLayout.addWidget(self.checkBox_Autocontrast, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.gridLayout_20.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_buttons_FIBSEM)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.button_get_image_FIB = QtWidgets.QPushButton(self.frame_2)
        self.button_get_image_FIB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_FIB.sizePolicy().hasHeightForWidth())
        self.button_get_image_FIB.setSizePolicy(sizePolicy)
        self.button_get_image_FIB.setObjectName("button_get_image_FIB")
        self.gridLayout_13.addWidget(self.button_get_image_FIB, 0, 0, 1, 1)
        self.button_get_image_SEM = QtWidgets.QPushButton(self.frame_2)
        self.button_get_image_SEM.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_get_image_SEM.sizePolicy().hasHeightForWidth())
        self.button_get_image_SEM.setSizePolicy(sizePolicy)
        self.button_get_image_SEM.setObjectName("button_get_image_SEM")
        self.gridLayout_13.addWidget(self.button_get_image_SEM, 0, 1, 1, 1)
        self.button_last_image_FIB = QtWidgets.QPushButton(self.frame_2)
        self.button_last_image_FIB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_last_image_FIB.sizePolicy().hasHeightForWidth())
        self.button_last_image_FIB.setSizePolicy(sizePolicy)
        self.button_last_image_FIB.setObjectName("button_last_image_FIB")
        self.gridLayout_13.addWidget(self.button_last_image_FIB, 1, 0, 1, 1)
        self.button_last_image_SEM = QtWidgets.QPushButton(self.frame_2)
        self.button_last_image_SEM.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_last_image_SEM.sizePolicy().hasHeightForWidth())
        self.button_last_image_SEM.setSizePolicy(sizePolicy)
        self.button_last_image_SEM.setObjectName("button_last_image_SEM")
        self.gridLayout_13.addWidget(self.button_last_image_SEM, 1, 1, 1, 1)
        self.gridLayout_20.addWidget(self.frame_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_buttons_FIBSEM)
        self.frame_save_destination_FIBSEM = QtWidgets.QFrame(self.frame_FIBSEM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_save_destination_FIBSEM.sizePolicy().hasHeightForWidth())
        self.frame_save_destination_FIBSEM.setSizePolicy(sizePolicy)
        self.frame_save_destination_FIBSEM.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_save_destination_FIBSEM.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_save_destination_FIBSEM.setObjectName("frame_save_destination_FIBSEM")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_save_destination_FIBSEM)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_save_filename_FIBSEM = QtWidgets.QLabel(self.frame_save_destination_FIBSEM)
        self.label_save_filename_FIBSEM.setObjectName("label_save_filename_FIBSEM")
        self.gridLayout_7.addWidget(self.label_save_filename_FIBSEM, 3, 0, 1, 1)
        self.label_save_destination_FIBSEM = QtWidgets.QLabel(self.frame_save_destination_FIBSEM)
        self.label_save_destination_FIBSEM.setObjectName("label_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.label_save_destination_FIBSEM, 1, 0, 1, 1)
        self.lineEdit_save_destination_FIBSEM = QtWidgets.QLineEdit(self.frame_save_destination_FIBSEM)
        self.lineEdit_save_destination_FIBSEM.setMinimumSize(QtCore.QSize(400, 20))
        self.lineEdit_save_destination_FIBSEM.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lineEdit_save_destination_FIBSEM.setObjectName("lineEdit_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.lineEdit_save_destination_FIBSEM, 1, 1, 1, 2)
        self.pushButton_load_FIBSEM = QtWidgets.QPushButton(self.frame_save_destination_FIBSEM)
        self.pushButton_load_FIBSEM.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_load_FIBSEM.setObjectName("pushButton_load_FIBSEM")
        self.gridLayout_7.addWidget(self.pushButton_load_FIBSEM, 1, 4, 1, 1)
        self.pushButton_save_FIBSEM = QtWidgets.QPushButton(self.frame_save_destination_FIBSEM)
        self.pushButton_save_FIBSEM.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_save_FIBSEM.setObjectName("pushButton_save_FIBSEM")
        self.gridLayout_7.addWidget(self.pushButton_save_FIBSEM, 3, 4, 1, 1)
        self.button_save_destination_FIBSEM = QtWidgets.QToolButton(self.frame_save_destination_FIBSEM)
        self.button_save_destination_FIBSEM.setMinimumSize(QtCore.QSize(25, 25))
        self.button_save_destination_FIBSEM.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_save_destination_FIBSEM.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.button_save_destination_FIBSEM.setObjectName("button_save_destination_FIBSEM")
        self.gridLayout_7.addWidget(self.button_save_destination_FIBSEM, 1, 3, 1, 1)
        self.lineEdit_save_filename_FIBSEM = QtWidgets.QLineEdit(self.frame_save_destination_FIBSEM)
        self.lineEdit_save_filename_FIBSEM.setObjectName("lineEdit_save_filename_FIBSEM")
        self.gridLayout_7.addWidget(self.lineEdit_save_filename_FIBSEM, 3, 1, 1, 3)
        self.verticalLayout.addWidget(self.frame_save_destination_FIBSEM)
        self.horizontalLayout.addWidget(self.frame_FIBSEM)
        self.frame_8 = QtWidgets.QFrame(self.Main_Frame)
        self.frame_8.setMinimumSize(QtCore.QSize(250, 40))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 1, 0, 1, 1)
        self.frame_connections = QtWidgets.QFrame(self.frame_8)
        self.frame_connections.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_connections.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_connections.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_connections.setObjectName("frame_connections")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_connections)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_25 = QtWidgets.QLabel(self.frame_connections)
        self.label_25.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_2.addWidget(self.label_25)
        self.label_28 = QtWidgets.QLabel(self.frame_connections)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_2.addWidget(self.label_28)
        self.pushButton_connect_microscope = QtWidgets.QPushButton(self.frame_connections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_connect_microscope.sizePolicy().hasHeightForWidth())
        self.pushButton_connect_microscope.setSizePolicy(sizePolicy)
        self.pushButton_connect_microscope.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_connect_microscope.setObjectName("pushButton_connect_microscope")
        self.verticalLayout_2.addWidget(self.pushButton_connect_microscope)
        self.pushButton_connect_detector = QtWidgets.QPushButton(self.frame_connections)
        self.pushButton_connect_detector.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_connect_detector.setObjectName("pushButton_connect_detector")
        self.verticalLayout_2.addWidget(self.pushButton_connect_detector)
        self.pushButton_connect_laser_controller = QtWidgets.QPushButton(self.frame_connections)
        self.pushButton_connect_laser_controller.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_connect_laser_controller.setObjectName("pushButton_connect_laser_controller")
        self.verticalLayout_2.addWidget(self.pushButton_connect_laser_controller)
        self.pushButton_connect_objective = QtWidgets.QPushButton(self.frame_connections)
        self.pushButton_connect_objective.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_connect_objective.setObjectName("pushButton_connect_objective")
        self.verticalLayout_2.addWidget(self.pushButton_connect_objective)
        self.pushButton_connect_mirror_controller = QtWidgets.QPushButton(self.frame_connections)
        self.pushButton_connect_mirror_controller.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_connect_mirror_controller.setObjectName("pushButton_connect_mirror_controller")
        self.verticalLayout_2.addWidget(self.pushButton_connect_mirror_controller)
        self.pushButton_connect_arduino = QtWidgets.QPushButton(self.frame_connections)
        self.pushButton_connect_arduino.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_connect_arduino.setObjectName("pushButton_connect_arduino")
        self.verticalLayout_2.addWidget(self.pushButton_connect_arduino)
        self.gridLayout_10.addWidget(self.frame_connections, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_save_filename_FIBSEM_3 = QtWidgets.QLabel(self.frame_5)
        self.label_save_filename_FIBSEM_3.setObjectName("label_save_filename_FIBSEM_3")
        self.gridLayout_9.addWidget(self.label_save_filename_FIBSEM_3, 3, 0, 1, 1)
        self.pushButton_correlation = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_correlation.setEnabled(False)
        self.pushButton_correlation.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_correlation.setObjectName("pushButton_correlation")
        self.gridLayout_9.addWidget(self.pushButton_correlation, 4, 0, 1, 3)
        self.label_save_filename_FIBSEM_2 = QtWidgets.QLabel(self.frame_5)
        self.label_save_filename_FIBSEM_2.setObjectName("label_save_filename_FIBSEM_2")
        self.gridLayout_9.addWidget(self.label_save_filename_FIBSEM_2, 2, 0, 1, 1)
        self.correlation_output_path = QtWidgets.QLineEdit(self.frame_5)
        self.correlation_output_path.setObjectName("correlation_output_path")
        self.gridLayout_9.addWidget(self.correlation_output_path, 2, 1, 1, 1)
        self.toolButton_correlation_output = QtWidgets.QToolButton(self.frame_5)
        self.toolButton_correlation_output.setMinimumSize(QtCore.QSize(25, 0))
        self.toolButton_correlation_output.setObjectName("toolButton_correlation_output")
        self.gridLayout_9.addWidget(self.toolButton_correlation_output, 2, 2, 1, 1)
        self.correlation_output_name = QtWidgets.QLineEdit(self.frame_5)
        self.correlation_output_name.setObjectName("correlation_output_name")
        self.gridLayout_9.addWidget(self.correlation_output_name, 3, 1, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_9.addWidget(self.label_29, 1, 0, 1, 3)
        self.label_26 = QtWidgets.QLabel(self.frame_5)
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_9.addWidget(self.label_26, 0, 0, 1, 3)
        self.gridLayout_10.addWidget(self.frame_5, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_16.setContentsMargins(-1, 1, -1, 1)
        self.gridLayout_16.setVerticalSpacing(3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_10.addWidget(self.frame, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_8)
        MainGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1850, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menuFile)
        self.menuHelp.setObjectName("menuHelp")
        MainGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainGui)
        self.statusbar.setObjectName("statusbar")
        MainGui.setStatusBar(self.statusbar)
        self.actionOpen_FM_Image = QtWidgets.QAction(MainGui)
        self.actionOpen_FM_Image.setObjectName("actionOpen_FM_Image")
        self.actionOpen_FIBSEM_Image = QtWidgets.QAction(MainGui)
        self.actionOpen_FIBSEM_Image.setObjectName("actionOpen_FIBSEM_Image")
        self.actionSave_FM_Image = QtWidgets.QAction(MainGui)
        self.actionSave_FM_Image.setObjectName("actionSave_FM_Image")
        self.actionSave_FIBSEM_Image = QtWidgets.QAction(MainGui)
        self.actionSave_FIBSEM_Image.setObjectName("actionSave_FIBSEM_Image")
        self.actionAbout = QtWidgets.QAction(MainGui)
        self.actionAbout.setObjectName("actionAbout")
        self.menuOpen.addAction(self.actionOpen_FM_Image)
        self.menuOpen.addAction(self.actionOpen_FIBSEM_Image)
        self.menuSave.addAction(self.actionSave_FM_Image)
        self.menuSave.addAction(self.actionSave_FIBSEM_Image)
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainGui)
        QtCore.QMetaObject.connectSlotsByName(MainGui)
        MainGui.setTabOrder(self.doubleSpinBox_laser1, self.lineEdit_exposure_1)
        MainGui.setTabOrder(self.lineEdit_exposure_1, self.doubleSpinBox_laser2)
        MainGui.setTabOrder(self.doubleSpinBox_laser2, self.lineEdit_exposure_2)
        MainGui.setTabOrder(self.lineEdit_exposure_2, self.doubleSpinBox_laser3)
        MainGui.setTabOrder(self.doubleSpinBox_laser3, self.lineEdit_exposure_3)
        MainGui.setTabOrder(self.lineEdit_exposure_3, self.doubleSpinBox_laser4)
        MainGui.setTabOrder(self.doubleSpinBox_laser4, self.lineEdit_exposure_4)
        MainGui.setTabOrder(self.lineEdit_exposure_4, self.checkBox_laser1)
        MainGui.setTabOrder(self.checkBox_laser1, self.checkBox_laser2)
        MainGui.setTabOrder(self.checkBox_laser2, self.checkBox_laser3)
        MainGui.setTabOrder(self.checkBox_laser3, self.checkBox_laser4)
        MainGui.setTabOrder(self.checkBox_laser4, self.lineEdit_slice_distance)
        MainGui.setTabOrder(self.lineEdit_slice_distance, self.lineEdit_volume_height)
        MainGui.setTabOrder(self.lineEdit_volume_height, self.pushButton_volume)
        MainGui.setTabOrder(self.pushButton_volume, self.pushButton_go_to_saved_position)
        MainGui.setTabOrder(self.pushButton_go_to_saved_position, self.pushButton_move_absolute)
        MainGui.setTabOrder(self.pushButton_move_absolute, self.lineEdit_move_absolute)
        MainGui.setTabOrder(self.lineEdit_move_absolute, self.pushButton_move_relative)
        MainGui.setTabOrder(self.pushButton_move_relative, self.lineEdit_move_relative)
        MainGui.setTabOrder(self.lineEdit_move_relative, self.toolButton_negative)
        MainGui.setTabOrder(self.toolButton_negative, self.toolButton_positive)
        MainGui.setTabOrder(self.toolButton_positive, self.pushButton_stage_movement)
        MainGui.setTabOrder(self.pushButton_stage_movement, self.button_get_image_FM)
        MainGui.setTabOrder(self.button_get_image_FM, self.button_live_image_FM)
        MainGui.setTabOrder(self.button_live_image_FM, self.comboBox_wavelength)
        MainGui.setTabOrder(self.comboBox_wavelength, self.comboBox_cmap)
        MainGui.setTabOrder(self.comboBox_cmap, self.comboBox_imaging_type)
        MainGui.setTabOrder(self.comboBox_imaging_type, self.comboBox_pattern)
        MainGui.setTabOrder(self.comboBox_pattern, self.lineEdit_save_destination_FM)
        MainGui.setTabOrder(self.lineEdit_save_destination_FM, self.button_save_destination_FM)
        MainGui.setTabOrder(self.button_save_destination_FM, self.lineEdit_save_filename_FM)
        MainGui.setTabOrder(self.lineEdit_save_filename_FM, self.pushButton_load_FM)
        MainGui.setTabOrder(self.pushButton_load_FM, self.pushButton_save_FM)
        MainGui.setTabOrder(self.pushButton_save_FM, self.button_get_image_FIB)
        MainGui.setTabOrder(self.button_get_image_FIB, self.button_get_image_SEM)
        MainGui.setTabOrder(self.button_get_image_SEM, self.button_last_image_FIB)
        MainGui.setTabOrder(self.button_last_image_FIB, self.button_last_image_SEM)
        MainGui.setTabOrder(self.button_last_image_SEM, self.lineEdit_dwell_time)
        MainGui.setTabOrder(self.lineEdit_dwell_time, self.comboBox_resolution)
        MainGui.setTabOrder(self.comboBox_resolution, self.checkBox_Autocontrast)
        MainGui.setTabOrder(self.checkBox_Autocontrast, self.lineEdit_save_destination_FIBSEM)
        MainGui.setTabOrder(self.lineEdit_save_destination_FIBSEM, self.button_save_destination_FIBSEM)
        MainGui.setTabOrder(self.button_save_destination_FIBSEM, self.lineEdit_save_filename_FIBSEM)
        MainGui.setTabOrder(self.lineEdit_save_filename_FIBSEM, self.pushButton_load_FIBSEM)
        MainGui.setTabOrder(self.pushButton_load_FIBSEM, self.pushButton_save_FIBSEM)
        MainGui.setTabOrder(self.pushButton_save_FIBSEM, self.pushButton_connect_microscope)
        MainGui.setTabOrder(self.pushButton_connect_microscope, self.pushButton_connect_detector)
        MainGui.setTabOrder(self.pushButton_connect_detector, self.pushButton_connect_laser_controller)
        MainGui.setTabOrder(self.pushButton_connect_laser_controller, self.pushButton_connect_objective)
        MainGui.setTabOrder(self.pushButton_connect_objective, self.pushButton_connect_mirror_controller)
        MainGui.setTabOrder(self.pushButton_connect_mirror_controller, self.pushButton_connect_arduino)
        MainGui.setTabOrder(self.pushButton_connect_arduino, self.pushButton_correlation)

    def retranslateUi(self, MainGui):
        _translate = QtCore.QCoreApplication.translate
        MainGui.setWindowTitle(_translate("MainGui", "PIEScope User Interface Main Window"))
        self.pushButton_move_relative.setText(_translate("MainGui", "Move Relative (um)"))
        self.label_5.setText(_translate("MainGui", "Note: positive is away from sample"))
        self.pushButton_go_to_saved_position.setText(_translate("MainGui", "Go to saved position"))
        self.label_23.setText(_translate("MainGui", "Light Microscope Objective"))
        self.pushButton_move_absolute.setText(_translate("MainGui", "Move Absolute (um)"))
        self.toolButton_negative.setText(_translate("MainGui", "-"))
        self.toolButton_positive.setText(_translate("MainGui", "+"))
        self.label_8.setText(_translate("MainGui", "Saved Position (um)"))
        self.label_7.setText(_translate("MainGui", "Absolute Position (um)"))
        self.label_22.setText(_translate("MainGui", "Movement"))
        self.pushButton_get_position.setText(_translate("MainGui", "Get Position"))
        self.pushButton_save_objective_position.setText(_translate("MainGui", "Save Position"))
        self.checkBox_laser4.setText(_translate("MainGui", "405nm"))
        self.label_20.setText(_translate("MainGui", "Volume Settings"))
        self.pushButton_volume.setText(_translate("MainGui", "Acquire Volume"))
        self.label_exposure_9.setText(_translate("MainGui", "Slice Distance (nm)"))
        self.checkBox_laser2.setText(_translate("MainGui", "561nm"))
        self.label_exposure_10.setText(_translate("MainGui", "Volume Height (nm)"))
        self.label_21.setText(_translate("MainGui", "Lasers for volume acquisition"))
        self.checkBox_laser1.setText(_translate("MainGui", "640nm"))
        self.checkBox_laser3.setText(_translate("MainGui", "488nm"))
        self.label_18.setText(_translate("MainGui", "Wavelength"))
        self.label_exposure_8.setText(_translate("MainGui", "Exposure time (ms)"))
        self.lineEdit_exposure_3.setText(_translate("MainGui", "1000"))
        self.label_19.setText(_translate("MainGui", "Power (%)"))
        self.label_17.setText(_translate("MainGui", "Laser Settings"))
        self.label_10.setText(_translate("MainGui", "640nm"))
        self.lineEdit_exposure_2.setText(_translate("MainGui", "1000"))
        self.label_11.setText(_translate("MainGui", "561nm"))
        self.label_12.setText(_translate("MainGui", "488nm"))
        self.lineEdit_exposure_1.setText(_translate("MainGui", "1000"))
        self.label_13.setText(_translate("MainGui", "405nm"))
        self.lineEdit_exposure_4.setText(_translate("MainGui", "1000"))
        self.pushButton_stage_movement.setText(_translate("MainGui", "Move To Other Microscope"))
        self.label_24.setText(_translate("MainGui", "Stage Movement"))
        self.label_FM.setText(_translate("MainGui", "Fluorescence Microscope"))
        self.button_get_image_FM.setText(_translate("MainGui", "Get Basler Image"))
        self.button_live_image_FM.setText(_translate("MainGui", "Live Basler View"))
        self.comboBox_imaging_type.setItemText(0, _translate("MainGui", "Widefield"))
        self.comboBox_imaging_type.setItemText(1, _translate("MainGui", "SIM"))
        self.label_16.setText(_translate("MainGui", "Imaging type:"))
        self.comboBox_cmap.setItemText(0, _translate("MainGui", "gray"))
        self.comboBox_cmap.setItemText(1, _translate("MainGui", "Reds_r"))
        self.comboBox_cmap.setItemText(2, _translate("MainGui", "Blues_r"))
        self.comboBox_cmap.setItemText(3, _translate("MainGui", "inferno"))
        self.comboBox_cmap.setItemText(4, _translate("MainGui", "magma"))
        self.comboBox_cmap.setItemText(5, _translate("MainGui", "hsv"))
        self.comboBox_cmap.setItemText(6, _translate("MainGui", "gist_rainbow"))
        self.comboBox_cmap.setItemText(7, _translate("MainGui", "jet"))
        self.comboBox_wavelength.setItemText(0, _translate("MainGui", "405 nm"))
        self.comboBox_wavelength.setItemText(1, _translate("MainGui", "488 nm"))
        self.comboBox_wavelength.setItemText(2, _translate("MainGui", "561 nm"))
        self.comboBox_wavelength.setItemText(3, _translate("MainGui", "640 nm"))
        self.label_14.setText(_translate("MainGui", "Wavelength:"))
        self.label_15.setText(_translate("MainGui", "Colour map:"))
        self.label.setText(_translate("MainGui", "Pattern: "))
        self.comboBox_pattern.setItemText(0, _translate("MainGui", "0 deg"))
        self.comboBox_pattern.setItemText(1, _translate("MainGui", "60 deg"))
        self.comboBox_pattern.setItemText(2, _translate("MainGui", "120 deg"))
        self.label_max_FM_value.setText(_translate("MainGui", "Max Value: "))
        self.label_save_filename_FM.setText(_translate("MainGui", "Save Filename"))
        self.pushButton_load_FM.setText(_translate("MainGui", "Load Image"))
        self.button_save_destination_FM.setText(_translate("MainGui", "..."))
        self.label_save_destination_FM.setText(_translate("MainGui", "Save Destination"))
        self.pushButton_save_FM.setText(_translate("MainGui", "Save Image"))
        self.label_FM_2.setText(_translate("MainGui", "Focused Ion Beam / Scanning Electron Microscope"))
        self.lineEdit_dwell_time.setText(_translate("MainGui", "1"))
        self.comboBox_resolution.setItemText(0, _translate("MainGui", "768x512"))
        self.comboBox_resolution.setItemText(1, _translate("MainGui", "1536x1024"))
        self.comboBox_resolution.setItemText(2, _translate("MainGui", "3072x2048"))
        self.comboBox_resolution.setItemText(3, _translate("MainGui", "6144x4096"))
        self.checkBox_Autocontrast.setText(_translate("MainGui", "Autocontrast"))
        self.label_3.setText(_translate("MainGui", "Dwell Time (us)"))
        self.label_4.setText(_translate("MainGui", "Resolution"))
        self.button_get_image_FIB.setText(_translate("MainGui", "Get FIB Image"))
        self.button_get_image_SEM.setText(_translate("MainGui", "Get SEM Image"))
        self.button_last_image_FIB.setText(_translate("MainGui", "Grab Last FIB Image"))
        self.button_last_image_SEM.setText(_translate("MainGui", "Grab Last SEM Image"))
        self.label_save_filename_FIBSEM.setText(_translate("MainGui", "Save Filename"))
        self.label_save_destination_FIBSEM.setText(_translate("MainGui", "Save Destination"))
        self.pushButton_load_FIBSEM.setText(_translate("MainGui", "Load Image"))
        self.pushButton_save_FIBSEM.setText(_translate("MainGui", "Save Image"))
        self.button_save_destination_FIBSEM.setText(_translate("MainGui", "..."))
        self.label_25.setText(_translate("MainGui", "Hardware Connections"))
        self.label_28.setText(_translate("MainGui", "Connect to:"))
        self.pushButton_connect_microscope.setText(_translate("MainGui", "FIBSEM Microscope"))
        self.pushButton_connect_detector.setText(_translate("MainGui", "Basler Detector"))
        self.pushButton_connect_laser_controller.setText(_translate("MainGui", "Laser Controller"))
        self.pushButton_connect_objective.setText(_translate("MainGui", "LM Objective"))
        self.pushButton_connect_mirror_controller.setText(_translate("MainGui", "Mirror Controller"))
        self.pushButton_connect_arduino.setText(_translate("MainGui", "Arduino"))
        self.label_save_filename_FIBSEM_3.setText(_translate("MainGui", "Save Filename"))
        self.pushButton_correlation.setText(_translate("MainGui", "Correlate Images"))
        self.label_save_filename_FIBSEM_2.setText(_translate("MainGui", "Save Filepath"))
        self.toolButton_correlation_output.setText(_translate("MainGui", "..."))
        self.label_29.setText(_translate("MainGui", "Correlation Save Destination"))
        self.label_26.setText(_translate("MainGui", "Correlation"))
        self.menuFile.setTitle(_translate("MainGui", "File"))
        self.menuOpen.setTitle(_translate("MainGui", "Open"))
        self.menuSave.setTitle(_translate("MainGui", "Save"))
        self.menuHelp.setTitle(_translate("MainGui", "Help"))
        self.actionOpen_FM_Image.setText(_translate("MainGui", "Open FM Image"))
        self.actionOpen_FIBSEM_Image.setText(_translate("MainGui", "Open FIBSEM Image"))
        self.actionSave_FM_Image.setText(_translate("MainGui", "Save FM Image"))
        self.actionSave_FIBSEM_Image.setText(_translate("MainGui", "Save FIBSEM Image"))
        self.actionAbout.setText(_translate("MainGui", "About"))

