# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'milling.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MillingWindow(object):
    def setupUi(self, MillingWindow):
        MillingWindow.setObjectName("MillingWindow")
        MillingWindow.resize(1084, 698)
        self.centralwidget = QtWidgets.QWidget(MillingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_parameters = QtWidgets.QFrame(self.frame_main)
        self.frame_parameters.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_parameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_parameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_parameters.setObjectName("frame_parameters")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_parameters)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.doubleSpinBox_center_distance = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_center_distance.setObjectName("doubleSpinBox_center_distance")
        self.gridLayout_4.addWidget(self.doubleSpinBox_center_distance, 5, 1, 1, 1)
        self.pushButton_save_position = QtWidgets.QPushButton(self.frame_parameters)
        self.pushButton_save_position.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_save_position.setStyleSheet("")
        self.pushButton_save_position.setObjectName("pushButton_save_position")
        self.gridLayout_4.addWidget(self.pushButton_save_position, 21, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.frame_parameters)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_parameters)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 17, 0, 1, 1)
        self.doubleSpinBox_trench_depth = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_trench_depth.setMaximum(20.0)
        self.doubleSpinBox_trench_depth.setObjectName("doubleSpinBox_trench_depth")
        self.gridLayout_4.addWidget(self.doubleSpinBox_trench_depth, 3, 1, 1, 1)
        self.doubleSpinBox_lower_width = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_lower_width.setObjectName("doubleSpinBox_lower_width")
        self.gridLayout_4.addWidget(self.doubleSpinBox_lower_width, 17, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_parameters)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 7, 0, 1, 2)
        self.doubleSpinBox_upper_width = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_upper_width.setObjectName("doubleSpinBox_upper_width")
        self.gridLayout_4.addWidget(self.doubleSpinBox_upper_width, 10, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_parameters)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 14, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_parameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 2)
        self.doubleSpinBox_upper_height = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_upper_height.setObjectName("doubleSpinBox_upper_height")
        self.gridLayout_4.addWidget(self.doubleSpinBox_upper_height, 8, 1, 1, 1)
        self.pushButton_start_milling = QtWidgets.QPushButton(self.frame_parameters)
        self.pushButton_start_milling.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_start_milling.setStyleSheet("")
        self.pushButton_start_milling.setObjectName("pushButton_start_milling")
        self.gridLayout_4.addWidget(self.pushButton_start_milling, 19, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.frame_parameters)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 8, 0, 1, 1)
        self.doubleSpinBox_lower_height = QtWidgets.QDoubleSpinBox(self.frame_parameters)
        self.doubleSpinBox_lower_height.setObjectName("doubleSpinBox_lower_height")
        self.gridLayout_4.addWidget(self.doubleSpinBox_lower_height, 14, 1, 1, 1)
        self.pushButton_stop_milling = QtWidgets.QPushButton(self.frame_parameters)
        self.pushButton_stop_milling.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_stop_milling.setStyleSheet("")
        self.pushButton_stop_milling.setObjectName("pushButton_stop_milling")
        self.gridLayout_4.addWidget(self.pushButton_stop_milling, 20, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.frame_parameters)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_parameters)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_parameters)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame_parameters)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 12, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 18, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 11, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 6, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frame_parameters, 0, 0, 2, 1)
        self.frame_image = QtWidgets.QFrame(self.frame_main)
        self.frame_image.setMaximumSize(QtCore.QSize(1536, 1024))
        self.frame_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_image)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_image = QtWidgets.QLabel(self.frame_image)
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.gridLayout_3.addWidget(self.label_image, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_image, 0, 1, 2, 1)
        self.gridLayout.addWidget(self.frame_main, 0, 0, 1, 1)
        MillingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MillingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 21))
        self.menubar.setObjectName("menubar")
        MillingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MillingWindow)
        self.statusbar.setObjectName("statusbar")
        MillingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MillingWindow)
        QtCore.QMetaObject.connectSlotsByName(MillingWindow)

    def retranslateUi(self, MillingWindow):
        _translate = QtCore.QCoreApplication.translate
        MillingWindow.setWindowTitle(_translate("MillingWindow", "Milling Window"))
        self.pushButton_save_position.setText(_translate("MillingWindow", "Save Position"))
        self.label_11.setText(_translate("MillingWindow", "Center Distance (μm)"))
        self.label_8.setText(_translate("MillingWindow", "Width (μm)"))
        self.label_4.setText(_translate("MillingWindow", "Upper Trench Parameters"))
        self.label_9.setText(_translate("MillingWindow", " Height (μm)"))
        self.label_2.setText(_translate("MillingWindow", "Milling Parameters"))
        self.pushButton_start_milling.setText(_translate("MillingWindow", "Start Milling"))
        self.label.setText(_translate("MillingWindow", " Height (μm)"))
        self.pushButton_stop_milling.setText(_translate("MillingWindow", "Stop Milling"))
        self.label_10.setText(_translate("MillingWindow", "Trench Depth (μm)"))
        self.label_7.setText(_translate("MillingWindow", "Width (μm)"))
        self.label_5.setText(_translate("MillingWindow", "Shared Parameters"))
        self.label_3.setText(_translate("MillingWindow", "Lower Trench Parameters"))

