# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainGui(object):
    def setupUi(self, MainGui):
        MainGui.setObjectName("MainGui")
        MainGui.resize(572, 734)
        MainGui.setMinimumSize(QtCore.QSize(572, 734))
        MainGui.setMaximumSize(QtCore.QSize(572, 734))
        self.centralwidget = QtWidgets.QWidget(MainGui)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setMinimumSize(QtCore.QSize(554, 675))
        self.frame_main.setMaximumSize(QtCore.QSize(554, 675))
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_main)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame_main)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_save_filename = QtWidgets.QLabel(self.frame_2)
        self.label_save_filename.setObjectName("label_save_filename")
        self.gridLayout.addWidget(self.label_save_filename, 0, 0, 1, 1)
        self.lineEdit_save_filename = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_save_filename.setObjectName("lineEdit_save_filename")
        self.gridLayout.addWidget(self.lineEdit_save_filename, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 6, 1, 1, 1)
        self.frame_save_destination = QtWidgets.QFrame(self.frame_main)
        self.frame_save_destination.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_save_destination.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_save_destination.setObjectName("frame_save_destination")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_save_destination)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_save_destination = QtWidgets.QLabel(self.frame_save_destination)
        self.label_save_destination.setObjectName("label_save_destination")
        self.gridLayout_5.addWidget(self.label_save_destination, 0, 0, 1, 1)
        self.checkBox_save_destination = QtWidgets.QCheckBox(self.frame_save_destination)
        self.checkBox_save_destination.setMinimumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination.setMaximumSize(QtCore.QSize(128, 17))
        self.checkBox_save_destination.setObjectName("checkBox_save_destination")
        self.gridLayout_5.addWidget(self.checkBox_save_destination, 0, 1, 1, 1)
        self.lineEdit_save_destination = QtWidgets.QLineEdit(self.frame_save_destination)
        self.lineEdit_save_destination.setMinimumSize(QtCore.QSize(480, 20))
        self.lineEdit_save_destination.setMaximumSize(QtCore.QSize(480, 20))
        self.lineEdit_save_destination.setObjectName("lineEdit_save_destination")
        self.gridLayout_5.addWidget(self.lineEdit_save_destination, 1, 0, 1, 1)
        self.button_save_destination = QtWidgets.QToolButton(self.frame_save_destination)
        self.button_save_destination.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_save_destination.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.button_save_destination.setObjectName("button_save_destination")
        self.gridLayout_5.addWidget(self.button_save_destination, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_4.addWidget(self.frame_save_destination, 5, 1, 1, 1)
        self.frame_slider = QtWidgets.QFrame(self.frame_main)
        self.frame_slider.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slider.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slider.setObjectName("frame_slider")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_slider)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layout_image_vertical = QtWidgets.QVBoxLayout()
        self.layout_image_vertical.setObjectName("layout_image_vertical")
        self.layout_image_horizontal = QtWidgets.QHBoxLayout()
        self.layout_image_horizontal.setObjectName("layout_image_horizontal")
        self.label_slider = QtWidgets.QLabel(self.frame_slider)
        self.label_slider.setObjectName("label_slider")
        self.layout_image_horizontal.addWidget(self.label_slider)
        spacerItem = QtWidgets.QSpacerItem(668, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_image_horizontal.addItem(spacerItem)
        self.spinbox_slider = QtWidgets.QSpinBox(self.frame_slider)
        self.spinbox_slider.setMinimumSize(QtCore.QSize(37, 20))
        self.spinbox_slider.setMaximumSize(QtCore.QSize(37, 20))
        self.spinbox_slider.setMinimum(1)
        self.spinbox_slider.setMaximum(1)
        self.spinbox_slider.setProperty("value", 1)
        self.spinbox_slider.setObjectName("spinbox_slider")
        self.layout_image_horizontal.addWidget(self.spinbox_slider)
        self.layout_image_vertical.addLayout(self.layout_image_horizontal)
        self.slider_stack = QtWidgets.QSlider(self.frame_slider)
        self.slider_stack.setMinimum(1)
        self.slider_stack.setMaximum(1)
        self.slider_stack.setSingleStep(1)
        self.slider_stack.setProperty("value", 1)
        self.slider_stack.setOrientation(QtCore.Qt.Horizontal)
        self.slider_stack.setObjectName("slider_stack")
        self.layout_image_vertical.addWidget(self.slider_stack)
        self.gridLayout_2.addLayout(self.layout_image_vertical, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_slider, 4, 1, 1, 1)
        self.frame_image = QtWidgets.QFrame(self.frame_main)
        self.frame_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_image)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_Emit = QtWidgets.QCheckBox(self.frame_image)
        self.checkBox_Emit.setObjectName("checkBox_Emit")
        self.gridLayout_3.addWidget(self.checkBox_Emit, 2, 1, 1, 1)
        self.comboBox_Laser = QtWidgets.QComboBox(self.frame_image)
        self.comboBox_Laser.setObjectName("comboBox_Laser")
        self.comboBox_Laser.addItem("")
        self.comboBox_Laser.addItem("")
        self.comboBox_Laser.addItem("")
        self.comboBox_Laser.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_Laser, 0, 0, 1, 1)
        self.spinBox_level = QtWidgets.QSpinBox(self.frame_image)
        self.spinBox_level.setMaximum(100)
        self.spinBox_level.setObjectName("spinBox_level")
        self.gridLayout_3.addWidget(self.spinBox_level, 0, 1, 1, 1)
        self.checkBox_Enabled = QtWidgets.QCheckBox(self.frame_image)
        self.checkBox_Enabled.setObjectName("checkBox_Enabled")
        self.gridLayout_3.addWidget(self.checkBox_Enabled, 2, 0, 1, 1)
        self.label_image = QtWidgets.QLabel(self.frame_image)
        self.label_image.setText("")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.gridLayout_3.addWidget(self.label_image, 3, 0, 1, 1)
        self.button_power = QtWidgets.QPushButton(self.frame_image)
        self.button_power.setEnabled(True)
        self.button_power.setMaximumSize(QtCore.QSize(60, 16777215))
        self.button_power.setObjectName("button_power")
        self.gridLayout_3.addWidget(self.button_power, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_image, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 1, 1, 1)
        self.button_live_basler = QtWidgets.QPushButton(self.frame_main)
        self.button_live_basler.setObjectName("button_live_basler")
        self.gridLayout_4.addWidget(self.button_live_basler, 8, 1, 1, 1)
        self.button_get_basler = QtWidgets.QPushButton(self.frame_main)
        self.button_get_basler.setObjectName("button_get_basler")
        self.gridLayout_4.addWidget(self.button_get_basler, 7, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame_main, 0, 0, 1, 1)
        MainGui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 572, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainGui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainGui)
        self.statusbar.setObjectName("statusbar")
        MainGui.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainGui)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainGui)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainGui)
        self.spinbox_slider.valueChanged['int'].connect(self.slider_stack.setValue)
        self.slider_stack.valueChanged['int'].connect(self.spinbox_slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainGui)

    def retranslateUi(self, MainGui):
        _translate = QtCore.QCoreApplication.translate
        MainGui.setWindowTitle(_translate("MainGui", "MainWindow"))
        self.label_save_filename.setText(_translate("MainGui", "Save Filename"))
        self.label_save_destination.setText(_translate("MainGui", "Save Destination"))
        self.checkBox_save_destination.setText(_translate("MainGui", "Lock Save Destination"))
        self.button_save_destination.setText(_translate("MainGui", "..."))
        self.label_slider.setText(_translate("MainGui", "Stack Slider"))
        self.checkBox_Emit.setText(_translate("MainGui", "Emit"))
        self.comboBox_Laser.setItemText(0, _translate("MainGui", "Laser 1"))
        self.comboBox_Laser.setItemText(1, _translate("MainGui", "Laser 2"))
        self.comboBox_Laser.setItemText(2, _translate("MainGui", "Laser 3"))
        self.comboBox_Laser.setItemText(3, _translate("MainGui", "Laser 4"))
        self.checkBox_Enabled.setText(_translate("MainGui", "Enabled"))
        self.button_power.setText(_translate("MainGui", "Power"))
        self.button_live_basler.setText(_translate("MainGui", "Live Basler View"))
        self.button_get_basler.setText(_translate("MainGui", "Get Basler Image"))
        self.menuFile.setTitle(_translate("MainGui", "File"))
        self.actionOpen.setText(_translate("MainGui", "Open"))
        self.actionSave.setText(_translate("MainGui", "Save"))


